#include "dbg_common.h"

#ifdef _DEBUG

extern NAME_VALUE_PAIR<UINT> tv_message[];

const wchar *debugGetTreeViewMessage(UINT msg)
{
	const wchar *ret;
	static wchar buf[64];
	ret=value_to_name(msg,L"",tv_message);
	if(*ret==L'\0'){
		swprintf(buf,L"UNDEFINED_MESSAGE(%d)",msg);
		ret=buf;
	}
	return ret;
}
static NAME_VALUE_PAIR<UINT> tv_message[]={
L"TVM_INSERTITEMA",	TVM_INSERTITEMA,
L"TVM_INSERTITEMW",	TVM_INSERTITEMW,
L"TVM_DELETEITEM",	TVM_DELETEITEM,
L"TVM_EXPAND",	TVM_EXPAND,
L"TVM_GETITEMRECT",	TVM_GETITEMRECT,
L"TVM_GETCOUNT",	TVM_GETCOUNT,
L"TVM_GETINDENT",	TVM_GETINDENT,
L"TVM_SETINDENT",	TVM_SETINDENT,
L"TVM_GETIMAGELIST",	TVM_GETIMAGELIST,
L"TVM_SETIMAGELIST",	TVM_SETIMAGELIST,
L"TVM_GETNEXTITEM",	TVM_GETNEXTITEM,
L"TVM_SELECTITEM",	TVM_SELECTITEM,
L"TVM_GETITEMA",	TVM_GETITEMA,
L"TVM_GETITEMW",	TVM_GETITEMW,
L"TVM_SETITEMA",	TVM_SETITEMA,
L"TVM_SETITEMW",	TVM_SETITEMW,
L"TVM_EDITLABELA",	TVM_EDITLABELA,
L"TVM_EDITLABELW",	TVM_EDITLABELW,
L"TVM_EDITLABEL",	TVM_EDITLABEL,
L"TVM_EDITLABEL",	TVM_EDITLABEL,
L"TVM_GETEDITCONTROL",	TVM_GETEDITCONTROL,
L"TVM_GETVISIBLECOUNT",	TVM_GETVISIBLECOUNT,
L"TVM_HITTEST",	TVM_HITTEST,
L"TVM_CREATEDRAGIMAGE",	TVM_CREATEDRAGIMAGE,
L"TVM_SORTCHILDREN",	TVM_SORTCHILDREN,
L"TVM_ENSUREVISIBLE",	TVM_ENSUREVISIBLE,
L"TVM_SORTCHILDRENCB",	TVM_SORTCHILDRENCB,
L"TVM_ENDEDITLABELNOW",	TVM_ENDEDITLABELNOW,
L"TVM_GETISEARCHSTRINGA",	TVM_GETISEARCHSTRINGA,
L"TVM_GETISEARCHSTRINGW",	TVM_GETISEARCHSTRINGW,
L"TVM_GETISEARCHSTRING",	TVM_GETISEARCHSTRING,
L"TVM_GETISEARCHSTRING",	TVM_GETISEARCHSTRING,
L"TVM_SETTOOLTIPS",	TVM_SETTOOLTIPS,
L"TVM_GETTOOLTIPS",	TVM_GETTOOLTIPS,
L"TVM_SETINSERTMARK",	TVM_SETINSERTMARK,
L"TVM_SETUNICODEFORMAT",	TVM_SETUNICODEFORMAT,
L"TVM_GETUNICODEFORMAT",	TVM_GETUNICODEFORMAT,
L"TVM_SETITEMHEIGHT",	TVM_SETITEMHEIGHT,
L"TVM_GETITEMHEIGHT",	TVM_GETITEMHEIGHT,
L"TVM_SETBKCOLOR",	TVM_SETBKCOLOR,
L"TVM_SETTEXTCOLOR",	TVM_SETTEXTCOLOR,
L"TVM_GETBKCOLOR",	TVM_GETBKCOLOR,
L"TVM_GETTEXTCOLOR",	TVM_GETTEXTCOLOR,
L"TVM_SETSCROLLTIME",	TVM_SETSCROLLTIME,
L"TVM_GETSCROLLTIME",	TVM_GETSCROLLTIME,
L"TVM_SETINSERTMARKCOLOR",	TVM_SETINSERTMARKCOLOR,
L"TVM_GETINSERTMARKCOLOR",	TVM_GETINSERTMARKCOLOR,
NULL,0,
};

extern NAME_VALUE_PAIR<UINT> tv_notify[];
const wchar *debugGetTreeViewNotify(UINT msg)
{
	const wchar *ret;
	static wchar buf[64];
	ret=value_to_name(msg,L"",tv_notify);
	if(*ret==L'\0'){
		swprintf(buf,L"UNDEFINED_MESSAGE(%x)",msg);
		ret=buf;
	}
	return ret;
}

static NAME_VALUE_PAIR<UINT> tv_notify[]={
L"TVN_FIRST",	TVN_FIRST,
L"TVN_LAST",	TVN_LAST,
L"TVN_SELCHANGINGA",	TVN_SELCHANGINGA,
L"TVN_SELCHANGINGW",	TVN_SELCHANGINGW,
L"TVN_SELCHANGEDA",	TVN_SELCHANGEDA,
L"TVN_SELCHANGEDW",	TVN_SELCHANGEDW,
L"TVN_GETDISPINFOA",	TVN_GETDISPINFOA,
L"TVN_GETDISPINFOW",	TVN_GETDISPINFOW,
L"TVN_SETDISPINFOA",	TVN_SETDISPINFOA,
L"TVN_SETDISPINFOW",	TVN_SETDISPINFOW,
L"TVN_ITEMEXPANDINGA",	TVN_ITEMEXPANDINGA,
L"TVN_ITEMEXPANDINGW",	TVN_ITEMEXPANDINGW,
L"TVN_ITEMEXPANDEDA",	TVN_ITEMEXPANDEDA,
L"TVN_ITEMEXPANDEDW",	TVN_ITEMEXPANDEDW,
L"TVN_BEGINDRAGA",	TVN_BEGINDRAGA,
L"TVN_BEGINDRAGW",	TVN_BEGINDRAGW,
L"TVN_BEGINRDRAGA",	TVN_BEGINRDRAGA,
L"TVN_BEGINRDRAGW",	TVN_BEGINRDRAGW,
L"TVN_DELETEITEMA",	TVN_DELETEITEMA,
L"TVN_DELETEITEMW",	TVN_DELETEITEMW,
L"TVN_BEGINLABELEDITA",	TVN_BEGINLABELEDITA,
L"TVN_BEGINLABELEDITW",	TVN_BEGINLABELEDITW,
L"TVN_ENDLABELEDITA",	TVN_ENDLABELEDITA,
L"TVN_ENDLABELEDITW",	TVN_ENDLABELEDITW,
L"TVN_KEYDOWN",	TVN_KEYDOWN,
L"TVN_GETINFOTIPA",	TVN_GETINFOTIPA,
L"TVN_GETINFOTIPW",	TVN_GETINFOTIPW,
L"TVN_SINGLEEXPAND",	TVN_SINGLEEXPAND,
L"TVN_SELCHANGING",	TVN_SELCHANGING,
L"TVN_SELCHANGED",	TVN_SELCHANGED,
L"TVN_GETDISPINFO",	TVN_GETDISPINFO,
L"TVN_SETDISPINFO",	TVN_SETDISPINFO,
L"TVN_ITEMEXPANDING",	TVN_ITEMEXPANDING,
L"TVN_ITEMEXPANDED",	TVN_ITEMEXPANDED,
L"TVN_BEGINDRAG",	TVN_BEGINDRAG,
L"TVN_BEGINRDRAG",	TVN_BEGINRDRAG,
L"TVN_DELETEITEM",	TVN_DELETEITEM,
L"TVN_BEGINLABELEDIT",	TVN_BEGINLABELEDIT,
L"TVN_ENDLABELEDIT",	TVN_ENDLABELEDIT,
L"TVN_SELCHANGING",	TVN_SELCHANGING,
L"TVN_SELCHANGED",	TVN_SELCHANGED,
L"TVN_GETDISPINFO",	TVN_GETDISPINFO,
L"TVN_SETDISPINFO",	TVN_SETDISPINFO,
L"TVN_ITEMEXPANDING",	TVN_ITEMEXPANDING,
L"TVN_ITEMEXPANDED",	TVN_ITEMEXPANDED,
L"TVN_BEGINDRAG",	TVN_BEGINDRAG,
L"TVN_BEGINRDRAG",	TVN_BEGINRDRAG,
L"TVN_DELETEITEM",	TVN_DELETEITEM,
L"TVN_BEGINLABELEDIT",	TVN_BEGINLABELEDIT,
L"TVN_ENDLABELEDIT",	TVN_ENDLABELEDIT,
L"TVN_GETINFOTIP",	TVN_GETINFOTIP,
L"TVN_GETINFOTIP",	TVN_GETINFOTIP,
NULL,0,
};

#endif
