#include "common/_required.h"
#include <StringLib.h>
using namespace util;
#include "dbg_common.h"
#include <Windows.h>
#include <MMSystem.h>

#ifndef _DEBUG
void debugprintf_dummy(const wchar *format,...)
{
}
#endif

#ifdef _DEBUG

void debugprintf(const wchar *format,...)
{
	va_list mark;
	va_start(mark,format);
	OutputDebugString(tmp_vswprintf(format,mark));
	va_end(mark);
}



/*
{HOME}{F3}+{END}{DEL}{DOWN}

{HOME}+{END}^C"^V",{TAB}^V,{DOWN}

*/




extern NAME_VALUE_PAIR<DWORD> mixer_control_type[];
const wchar *debugGetMixerControlType(DWORD dwControlType)
{
	const wchar *ret;
	static wchar buf[64];
	ret=value_to_name(dwControlType,L"",mixer_control_type);
	if(*ret==L'\0'){
		swprintf(buf,L"UNDEFINED_TYPE(%d)",dwControlType);
		ret=buf;
	}
	return ret;
}

static NAME_VALUE_PAIR<DWORD> mixer_control_type[]={
L"MIXERCONTROL_CONTROLTYPE_CUSTOM",			MIXERCONTROL_CONTROLTYPE_CUSTOM,
L"MIXERCONTROL_CONTROLTYPE_BASS",			MIXERCONTROL_CONTROLTYPE_BASS,
L"MIXERCONTROL_CONTROLTYPE_EQUALIZER",		MIXERCONTROL_CONTROLTYPE_EQUALIZER,
L"MIXERCONTROL_CONTROLTYPE_FADER",			MIXERCONTROL_CONTROLTYPE_FADER,
L"MIXERCONTROL_CONTROLTYPE_TREBLE",			MIXERCONTROL_CONTROLTYPE_TREBLE,
L"MIXERCONTROL_CONTROLTYPE_VOLUME",			MIXERCONTROL_CONTROLTYPE_VOLUME,
L"MIXERCONTROL_CONTROLTYPE_MIXER",			MIXERCONTROL_CONTROLTYPE_MIXER,
L"MIXERCONTROL_CONTROLTYPE_MULTIPLESELECT",	MIXERCONTROL_CONTROLTYPE_MULTIPLESELECT,
L"MIXERCONTROL_CONTROLTYPE_MUX",				MIXERCONTROL_CONTROLTYPE_MUX,
L"MIXERCONTROL_CONTROLTYPE_SINGLESELECT ",	MIXERCONTROL_CONTROLTYPE_SINGLESELECT ,
L"MIXERCONTROL_CONTROLTYPE_BOOLEANMETER",	MIXERCONTROL_CONTROLTYPE_BOOLEANMETER,
L"MIXERCONTROL_CONTROLTYPE_PEAKMETER",		MIXERCONTROL_CONTROLTYPE_PEAKMETER,
L"MIXERCONTROL_CONTROLTYPE_SIGNEDMETER",		MIXERCONTROL_CONTROLTYPE_SIGNEDMETER,
L"MIXERCONTROL_CONTROLTYPE_UNSIGNEDMETER",	MIXERCONTROL_CONTROLTYPE_UNSIGNEDMETER,
L"MIXERCONTROL_CONTROLTYPE_DECIBELS",		MIXERCONTROL_CONTROLTYPE_DECIBELS,
L"MIXERCONTROL_CONTROLTYPE_PERCENT",			MIXERCONTROL_CONTROLTYPE_PERCENT,
L"MIXERCONTROL_CONTROLTYPE_SIGNED",			MIXERCONTROL_CONTROLTYPE_SIGNED,
L"MIXERCONTROL_CONTROLTYPE_UNSIGNED",		MIXERCONTROL_CONTROLTYPE_UNSIGNED,
L"MIXERCONTROL_CONTROLTYPE_PAN",				MIXERCONTROL_CONTROLTYPE_PAN,
L"MIXERCONTROL_CONTROLTYPE_QSOUNDPAN",		MIXERCONTROL_CONTROLTYPE_QSOUNDPAN,
L"MIXERCONTROL_CONTROLTYPE_SLIDER ",			MIXERCONTROL_CONTROLTYPE_SLIDER ,
L"MIXERCONTROL_CONTROLTYPE_BOOLEAN",			MIXERCONTROL_CONTROLTYPE_BOOLEAN,
L"MIXERCONTROL_CONTROLTYPE_BUTTON",			MIXERCONTROL_CONTROLTYPE_BUTTON,
L"MIXERCONTROL_CONTROLTYPE_LOUDNESS",		MIXERCONTROL_CONTROLTYPE_LOUDNESS,
L"MIXERCONTROL_CONTROLTYPE_MONO",			MIXERCONTROL_CONTROLTYPE_MONO,
L"MIXERCONTROL_CONTROLTYPE_MUTE",			MIXERCONTROL_CONTROLTYPE_MUTE,
L"MIXERCONTROL_CONTROLTYPE_ONOFF",			MIXERCONTROL_CONTROLTYPE_ONOFF,
L"MIXERCONTROL_CONTROLTYPE_STEREOENH",		MIXERCONTROL_CONTROLTYPE_STEREOENH,
L"MIXERCONTROL_CONTROLTYPE_MICROTIME",		MIXERCONTROL_CONTROLTYPE_MICROTIME,
L"MIXERCONTROL_CONTROLTYPE_MILLITIME",		MIXERCONTROL_CONTROLTYPE_MILLITIME,
NULL,	0,
};


extern NAME_VALUE_PAIR<DWORD> mixer_component_type[];
const wchar *debugGetMixerComponentType(DWORD dwComponentType)
{
	const wchar *ret;
	static wchar buf[64];
	ret=value_to_name(dwComponentType,L"",mixer_component_type);
	if(*ret==L'\0'){
		swprintf(buf,L"UNDEFINED_TYPE(%d)",dwComponentType);
		ret=buf;
	}
	return ret;
}

static NAME_VALUE_PAIR<DWORD> mixer_component_type[]={
L"MIXERLINE_COMPONENTTYPE_DST_DIGITAL",		MIXERLINE_COMPONENTTYPE_DST_DIGITAL,
L"MIXERLINE_COMPONENTTYPE_DST_HEADPHONES",	MIXERLINE_COMPONENTTYPE_DST_HEADPHONES,
L"MIXERLINE_COMPONENTTYPE_DST_LINE",			MIXERLINE_COMPONENTTYPE_DST_LINE,
L"MIXERLINE_COMPONENTTYPE_DST_MONITOR",		MIXERLINE_COMPONENTTYPE_DST_MONITOR,
L"MIXERLINE_COMPONENTTYPE_DST_SPEAKERS",		MIXERLINE_COMPONENTTYPE_DST_SPEAKERS,
L"MIXERLINE_COMPONENTTYPE_DST_TELEPHONE",	MIXERLINE_COMPONENTTYPE_DST_TELEPHONE,
L"MIXERLINE_COMPONENTTYPE_DST_UNDEFINED",	MIXERLINE_COMPONENTTYPE_DST_UNDEFINED,
L"MIXERLINE_COMPONENTTYPE_DST_VOICEIN",		MIXERLINE_COMPONENTTYPE_DST_VOICEIN,
L"MIXERLINE_COMPONENTTYPE_DST_WAVEIN",		MIXERLINE_COMPONENTTYPE_DST_WAVEIN,
L"MIXERLINE_COMPONENTTYPE_SRC_ANALOG",		MIXERLINE_COMPONENTTYPE_SRC_ANALOG,
L"MIXERLINE_COMPONENTTYPE_SRC_AUXILIARY",	MIXERLINE_COMPONENTTYPE_SRC_AUXILIARY,
L"MIXERLINE_COMPONENTTYPE_SRC_COMPACTDISC",	MIXERLINE_COMPONENTTYPE_SRC_COMPACTDISC,
L"MIXERLINE_COMPONENTTYPE_SRC_DIGITAL",		MIXERLINE_COMPONENTTYPE_SRC_DIGITAL,
L"MIXERLINE_COMPONENTTYPE_SRC_LINE",			MIXERLINE_COMPONENTTYPE_SRC_LINE,
L"MIXERLINE_COMPONENTTYPE_SRC_MICROPHONE",	MIXERLINE_COMPONENTTYPE_SRC_MICROPHONE,
L"MIXERLINE_COMPONENTTYPE_SRC_PCSPEAKER",	MIXERLINE_COMPONENTTYPE_SRC_PCSPEAKER,
L"MIXERLINE_COMPONENTTYPE_SRC_SYNTHESIZER",	MIXERLINE_COMPONENTTYPE_SRC_SYNTHESIZER,
L"MIXERLINE_COMPONENTTYPE_SRC_TELEPHONE",	MIXERLINE_COMPONENTTYPE_SRC_TELEPHONE,
L"MIXERLINE_COMPONENTTYPE_SRC_UNDEFINED",	MIXERLINE_COMPONENTTYPE_SRC_UNDEFINED,
L"MIXERLINE_COMPONENTTYPE_SRC_WAVEOUT",		MIXERLINE_COMPONENTTYPE_SRC_WAVEOUT,
NULL,	0,
};


extern NAME_VALUE_PAIR<int> error_name[];
const wchar *debugGetErrorName(int err)
{
	const wchar *ret;
	static wchar buf[64];
	ret=value_to_name(err,L"",error_name);
	if(*ret==L'\0'){
		swprintf(buf,L"UNDEFINED_NAME(%d)",err);
		ret=buf;
	}
	return ret;
}

//winuser.h
static NAME_VALUE_PAIR<int> error_name[]={
L"ERROR_SUCCESS",	ERROR_SUCCESS,
L"ERROR_INVALID_FUNCTION",	ERROR_INVALID_FUNCTION,
L"ERROR_FILE_NOT_FOUND",	ERROR_FILE_NOT_FOUND,
L"ERROR_PATH_NOT_FOUND",	ERROR_PATH_NOT_FOUND,
L"ERROR_TOO_MANY_OPEN_FILES",	ERROR_TOO_MANY_OPEN_FILES,
L"ERROR_ACCESS_DENIED",	ERROR_ACCESS_DENIED,
L"ERROR_INVALID_HANDLE",	ERROR_INVALID_HANDLE,
L"ERROR_ARENA_TRASHED",	ERROR_ARENA_TRASHED,
L"ERROR_NOT_ENOUGH_MEMORY",	ERROR_NOT_ENOUGH_MEMORY,
L"ERROR_INVALID_BLOCK",	ERROR_INVALID_BLOCK,
L"ERROR_BAD_ENVIRONMENT",	ERROR_BAD_ENVIRONMENT,
L"ERROR_BAD_FORMAT",	ERROR_BAD_FORMAT,
L"ERROR_INVALID_ACCESS",	ERROR_INVALID_ACCESS,
L"ERROR_INVALID_DATA",	ERROR_INVALID_DATA,
L"ERROR_OUTOFMEMORY",	ERROR_OUTOFMEMORY,
L"ERROR_INVALID_DRIVE",	ERROR_INVALID_DRIVE,
L"ERROR_CURRENT_DIRECTORY",	ERROR_CURRENT_DIRECTORY,
L"ERROR_NOT_SAME_DEVICE",	ERROR_NOT_SAME_DEVICE,
L"ERROR_NO_MORE_FILES",	ERROR_NO_MORE_FILES,
L"ERROR_WRITE_PROTECT",	ERROR_WRITE_PROTECT,
L"ERROR_BAD_UNIT",	ERROR_BAD_UNIT,
L"ERROR_NOT_READY",	ERROR_NOT_READY,
L"ERROR_BAD_COMMAND",	ERROR_BAD_COMMAND,
L"ERROR_CRC",	ERROR_CRC,
L"ERROR_BAD_LENGTH",	ERROR_BAD_LENGTH,
L"ERROR_SEEK",	ERROR_SEEK,
L"ERROR_NOT_DOS_DISK",	ERROR_NOT_DOS_DISK,
L"ERROR_SECTOR_NOT_FOUND",	ERROR_SECTOR_NOT_FOUND,
L"ERROR_OUT_OF_PAPER",	ERROR_OUT_OF_PAPER,
L"ERROR_WRITE_FAULT",	ERROR_WRITE_FAULT,
L"ERROR_READ_FAULT",	ERROR_READ_FAULT,
L"ERROR_GEN_FAILURE",	ERROR_GEN_FAILURE,
L"ERROR_SHARING_VIOLATION",	ERROR_SHARING_VIOLATION,
L"ERROR_LOCK_VIOLATION",	ERROR_LOCK_VIOLATION,
L"ERROR_WRONG_DISK",	ERROR_WRONG_DISK,
L"ERROR_SHARING_BUFFER_EXCEEDED",	ERROR_SHARING_BUFFER_EXCEEDED,
L"ERROR_HANDLE_EOF",	ERROR_HANDLE_EOF,
L"ERROR_HANDLE_DISK_FULL",	ERROR_HANDLE_DISK_FULL,
L"ERROR_NOT_SUPPORTED",	ERROR_NOT_SUPPORTED,
L"ERROR_REM_NOT_LIST",	ERROR_REM_NOT_LIST,
L"ERROR_DUP_NAME",	ERROR_DUP_NAME,
L"ERROR_BAD_NETPATH",	ERROR_BAD_NETPATH,
L"ERROR_NETWORK_BUSY",	ERROR_NETWORK_BUSY,
L"ERROR_DEV_NOT_EXIST",	ERROR_DEV_NOT_EXIST,
L"ERROR_TOO_MANY_CMDS",	ERROR_TOO_MANY_CMDS,
L"ERROR_ADAP_HDW_ERR",	ERROR_ADAP_HDW_ERR,
L"ERROR_BAD_NET_RESP",	ERROR_BAD_NET_RESP,
L"ERROR_UNEXP_NET_ERR",	ERROR_UNEXP_NET_ERR,
L"ERROR_BAD_REM_ADAP",	ERROR_BAD_REM_ADAP,
L"ERROR_PRINTQ_FULL",	ERROR_PRINTQ_FULL,
L"ERROR_NO_SPOOL_SPACE",	ERROR_NO_SPOOL_SPACE,
L"ERROR_PRINT_CANCELLED",	ERROR_PRINT_CANCELLED,
L"ERROR_NETNAME_DELETED",	ERROR_NETNAME_DELETED,
L"ERROR_NETWORK_ACCESS_DENIED",	ERROR_NETWORK_ACCESS_DENIED,
L"ERROR_BAD_DEV_TYPE",	ERROR_BAD_DEV_TYPE,
L"ERROR_BAD_NET_NAME",	ERROR_BAD_NET_NAME,
L"ERROR_TOO_MANY_NAMES",	ERROR_TOO_MANY_NAMES,
L"ERROR_TOO_MANY_SESS",	ERROR_TOO_MANY_SESS,
L"ERROR_SHARING_PAUSED",	ERROR_SHARING_PAUSED,
L"ERROR_REQ_NOT_ACCEP",	ERROR_REQ_NOT_ACCEP,
L"ERROR_REDIR_PAUSED",	ERROR_REDIR_PAUSED,
L"ERROR_FILE_EXISTS",	ERROR_FILE_EXISTS,
L"ERROR_CANNOT_MAKE",	ERROR_CANNOT_MAKE,
L"ERROR_FAIL_I24",	ERROR_FAIL_I24,
L"ERROR_OUT_OF_STRUCTURES",	ERROR_OUT_OF_STRUCTURES,
L"ERROR_ALREADY_ASSIGNED",	ERROR_ALREADY_ASSIGNED,
L"ERROR_INVALID_PASSWORD",	ERROR_INVALID_PASSWORD,
L"ERROR_INVALID_PARAMETER",	ERROR_INVALID_PARAMETER,
L"ERROR_NET_WRITE_FAULT",	ERROR_NET_WRITE_FAULT,
L"ERROR_NO_PROC_SLOTS",	ERROR_NO_PROC_SLOTS,
L"ERROR_TOO_MANY_SEMAPHORES",	ERROR_TOO_MANY_SEMAPHORES,
L"ERROR_EXCL_SEM_ALREADY_OWNED",	ERROR_EXCL_SEM_ALREADY_OWNED,
L"ERROR_SEM_IS_SET",	ERROR_SEM_IS_SET,
L"ERROR_TOO_MANY_SEM_REQUESTS",	ERROR_TOO_MANY_SEM_REQUESTS,
L"ERROR_INVALID_AT_INTERRUPT_TIME",	ERROR_INVALID_AT_INTERRUPT_TIME,
L"ERROR_SEM_OWNER_DIED",	ERROR_SEM_OWNER_DIED,
L"ERROR_SEM_USER_LIMIT",	ERROR_SEM_USER_LIMIT,
L"ERROR_DISK_CHANGE",	ERROR_DISK_CHANGE,
L"ERROR_DRIVE_LOCKED",	ERROR_DRIVE_LOCKED,
L"ERROR_BROKEN_PIPE",	ERROR_BROKEN_PIPE,
L"ERROR_OPEN_FAILED",	ERROR_OPEN_FAILED,
L"ERROR_BUFFER_OVERFLOW",	ERROR_BUFFER_OVERFLOW,
L"ERROR_DISK_FULL",	ERROR_DISK_FULL,
L"ERROR_NO_MORE_SEARCH_HANDLES",	ERROR_NO_MORE_SEARCH_HANDLES,
L"ERROR_INVALID_TARGET_HANDLE",	ERROR_INVALID_TARGET_HANDLE,
L"ERROR_INVALID_CATEGORY",	ERROR_INVALID_CATEGORY,
L"ERROR_INVALID_VERIFY_SWITCH",	ERROR_INVALID_VERIFY_SWITCH,
L"ERROR_BAD_DRIVER_LEVEL",	ERROR_BAD_DRIVER_LEVEL,
L"ERROR_CALL_NOT_IMPLEMENTED",	ERROR_CALL_NOT_IMPLEMENTED,
L"ERROR_SEM_TIMEOUT",	ERROR_SEM_TIMEOUT,
L"ERROR_INSUFFICIENT_BUFFER",	ERROR_INSUFFICIENT_BUFFER,
L"ERROR_INVALID_NAME",	ERROR_INVALID_NAME,
L"ERROR_INVALID_LEVEL",	ERROR_INVALID_LEVEL,
L"ERROR_NO_VOLUME_LABEL",	ERROR_NO_VOLUME_LABEL,
L"ERROR_MOD_NOT_FOUND",	ERROR_MOD_NOT_FOUND,
L"ERROR_PROC_NOT_FOUND",	ERROR_PROC_NOT_FOUND,
L"ERROR_WAIT_NO_CHILDREN",	ERROR_WAIT_NO_CHILDREN,
L"ERROR_CHILD_NOT_COMPLETE",	ERROR_CHILD_NOT_COMPLETE,
L"ERROR_DIRECT_ACCESS_HANDLE",	ERROR_DIRECT_ACCESS_HANDLE,
L"ERROR_NEGATIVE_SEEK",	ERROR_NEGATIVE_SEEK,
L"ERROR_SEEK_ON_DEVICE",	ERROR_SEEK_ON_DEVICE,
L"ERROR_IS_JOIN_TARGET",	ERROR_IS_JOIN_TARGET,
L"ERROR_IS_JOINED",	ERROR_IS_JOINED,
L"ERROR_IS_SUBSTED",	ERROR_IS_SUBSTED,
L"ERROR_NOT_JOINED",	ERROR_NOT_JOINED,
L"ERROR_NOT_SUBSTED",	ERROR_NOT_SUBSTED,
L"ERROR_JOIN_TO_JOIN",	ERROR_JOIN_TO_JOIN,
L"ERROR_SUBST_TO_SUBST",	ERROR_SUBST_TO_SUBST,
L"ERROR_JOIN_TO_SUBST",	ERROR_JOIN_TO_SUBST,
L"ERROR_SUBST_TO_JOIN",	ERROR_SUBST_TO_JOIN,
L"ERROR_BUSY_DRIVE",	ERROR_BUSY_DRIVE,
L"ERROR_SAME_DRIVE",	ERROR_SAME_DRIVE,
L"ERROR_DIR_NOT_ROOT",	ERROR_DIR_NOT_ROOT,
L"ERROR_DIR_NOT_EMPTY",	ERROR_DIR_NOT_EMPTY,
L"ERROR_IS_SUBST_PATH",	ERROR_IS_SUBST_PATH,
L"ERROR_IS_JOIN_PATH",	ERROR_IS_JOIN_PATH,
L"ERROR_PATH_BUSY",	ERROR_PATH_BUSY,
L"ERROR_IS_SUBST_TARGET",	ERROR_IS_SUBST_TARGET,
L"ERROR_SYSTEM_TRACE",	ERROR_SYSTEM_TRACE,
L"ERROR_INVALID_EVENT_COUNT",	ERROR_INVALID_EVENT_COUNT,
L"ERROR_TOO_MANY_MUXWAITERS",	ERROR_TOO_MANY_MUXWAITERS,
L"ERROR_INVALID_LIST_FORMAT",	ERROR_INVALID_LIST_FORMAT,
L"ERROR_LABEL_TOO_LONG",	ERROR_LABEL_TOO_LONG,
L"ERROR_TOO_MANY_TCBS",	ERROR_TOO_MANY_TCBS,
L"ERROR_SIGNAL_REFUSED",	ERROR_SIGNAL_REFUSED,
L"ERROR_DISCARDED",	ERROR_DISCARDED,
L"ERROR_NOT_LOCKED",	ERROR_NOT_LOCKED,
L"ERROR_BAD_THREADID_ADDR",	ERROR_BAD_THREADID_ADDR,
L"ERROR_BAD_ARGUMENTS",	ERROR_BAD_ARGUMENTS,
L"ERROR_BAD_PATHNAME",	ERROR_BAD_PATHNAME,
L"ERROR_SIGNAL_PENDING",	ERROR_SIGNAL_PENDING,
L"ERROR_MAX_THRDS_REACHED",	ERROR_MAX_THRDS_REACHED,
L"ERROR_LOCK_FAILED",	ERROR_LOCK_FAILED,
L"ERROR_BUSY",	ERROR_BUSY,
L"ERROR_CANCEL_VIOLATION",	ERROR_CANCEL_VIOLATION,
L"ERROR_ATOMIC_LOCKS_NOT_SUPPORTED",	ERROR_ATOMIC_LOCKS_NOT_SUPPORTED,
L"ERROR_INVALID_SEGMENT_NUMBER",	ERROR_INVALID_SEGMENT_NUMBER,
L"ERROR_INVALID_ORDINAL",	ERROR_INVALID_ORDINAL,
L"ERROR_ALREADY_EXISTS",	ERROR_ALREADY_EXISTS,
L"ERROR_INVALID_FLAG_NUMBER",	ERROR_INVALID_FLAG_NUMBER,
L"ERROR_SEM_NOT_FOUND",	ERROR_SEM_NOT_FOUND,
L"ERROR_INVALID_STARTING_CODESEG",	ERROR_INVALID_STARTING_CODESEG,
L"ERROR_INVALID_STACKSEG",	ERROR_INVALID_STACKSEG,
L"ERROR_INVALID_MODULETYPE",	ERROR_INVALID_MODULETYPE,
L"ERROR_INVALID_EXE_SIGNATURE",	ERROR_INVALID_EXE_SIGNATURE,
L"ERROR_EXE_MARKED_INVALID",	ERROR_EXE_MARKED_INVALID,
L"ERROR_BAD_EXE_FORMAT",	ERROR_BAD_EXE_FORMAT,
L"ERROR_ITERATED_DATA_EXCEEDS_64k",	ERROR_ITERATED_DATA_EXCEEDS_64k,
L"ERROR_INVALID_MINALLOCSIZE",	ERROR_INVALID_MINALLOCSIZE,
L"ERROR_DYNLINK_FROM_INVALID_RING",	ERROR_DYNLINK_FROM_INVALID_RING,
L"ERROR_IOPL_NOT_ENABLED",	ERROR_IOPL_NOT_ENABLED,
L"ERROR_INVALID_SEGDPL",	ERROR_INVALID_SEGDPL,
L"ERROR_AUTODATASEG_EXCEEDS_64k",	ERROR_AUTODATASEG_EXCEEDS_64k,
L"ERROR_RING2SEG_MUST_BE_MOVABLE",	ERROR_RING2SEG_MUST_BE_MOVABLE,
L"ERROR_RELOC_CHAIN_XEEDS_SEGLIM",	ERROR_RELOC_CHAIN_XEEDS_SEGLIM,
L"ERROR_INFLOOP_IN_RELOC_CHAIN",	ERROR_INFLOOP_IN_RELOC_CHAIN,
L"ERROR_ENVVAR_NOT_FOUND",	ERROR_ENVVAR_NOT_FOUND,
L"ERROR_NO_SIGNAL_SENT",	ERROR_NO_SIGNAL_SENT,
L"ERROR_FILENAME_EXCED_RANGE",	ERROR_FILENAME_EXCED_RANGE,
L"ERROR_RING2_STACK_IN_USE",	ERROR_RING2_STACK_IN_USE,
L"ERROR_META_EXPANSION_TOO_LONG",	ERROR_META_EXPANSION_TOO_LONG,
L"ERROR_INVALID_SIGNAL_NUMBER",	ERROR_INVALID_SIGNAL_NUMBER,
L"ERROR_THREAD_1_INACTIVE",	ERROR_THREAD_1_INACTIVE,
L"ERROR_LOCKED",	ERROR_LOCKED,
L"ERROR_TOO_MANY_MODULES",	ERROR_TOO_MANY_MODULES,
L"ERROR_NESTING_NOT_ALLOWED",	ERROR_NESTING_NOT_ALLOWED,
L"ERROR_EXE_MACHINE_TYPE_MISMATCH",	ERROR_EXE_MACHINE_TYPE_MISMATCH,
L"ERROR_BAD_PIPE",	ERROR_BAD_PIPE,
L"ERROR_PIPE_BUSY",	ERROR_PIPE_BUSY,
L"ERROR_NO_DATA",	ERROR_NO_DATA,
L"ERROR_PIPE_NOT_CONNECTED",	ERROR_PIPE_NOT_CONNECTED,
L"ERROR_MORE_DATA",	ERROR_MORE_DATA,
L"ERROR_VC_DISCONNECTED",	ERROR_VC_DISCONNECTED,
L"ERROR_INVALID_EA_NAME",	ERROR_INVALID_EA_NAME,
L"ERROR_EA_LIST_INCONSISTENT",	ERROR_EA_LIST_INCONSISTENT,
L"ERROR_NO_MORE_ITEMS",	ERROR_NO_MORE_ITEMS,
L"ERROR_CANNOT_COPY",	ERROR_CANNOT_COPY,
L"ERROR_DIRECTORY",	ERROR_DIRECTORY,
L"ERROR_EAS_DIDNT_FIT",	ERROR_EAS_DIDNT_FIT,
L"ERROR_EA_FILE_CORRUPT",	ERROR_EA_FILE_CORRUPT,
L"ERROR_EA_TABLE_FULL",	ERROR_EA_TABLE_FULL,
L"ERROR_INVALID_EA_HANDLE",	ERROR_INVALID_EA_HANDLE,
L"ERROR_EAS_NOT_SUPPORTED",	ERROR_EAS_NOT_SUPPORTED,
L"ERROR_NOT_OWNER",	ERROR_NOT_OWNER,
L"ERROR_TOO_MANY_POSTS",	ERROR_TOO_MANY_POSTS,
L"ERROR_PARTIAL_COPY",	ERROR_PARTIAL_COPY,
L"ERROR_OPLOCK_NOT_GRANTED",	ERROR_OPLOCK_NOT_GRANTED,
L"ERROR_INVALID_OPLOCK_PROTOCOL",	ERROR_INVALID_OPLOCK_PROTOCOL,
L"ERROR_MR_MID_NOT_FOUND",	ERROR_MR_MID_NOT_FOUND,
L"ERROR_INVALID_ADDRESS",	ERROR_INVALID_ADDRESS,
L"ERROR_ARITHMETIC_OVERFLOW",	ERROR_ARITHMETIC_OVERFLOW,
L"ERROR_PIPE_CONNECTED",	ERROR_PIPE_CONNECTED,
L"ERROR_PIPE_LISTENING",	ERROR_PIPE_LISTENING,
L"ERROR_EA_ACCESS_DENIED",	ERROR_EA_ACCESS_DENIED,
L"ERROR_OPERATION_ABORTED",	ERROR_OPERATION_ABORTED,
L"ERROR_IO_INCOMPLETE",	ERROR_IO_INCOMPLETE,
L"ERROR_IO_PENDING",	ERROR_IO_PENDING,
L"ERROR_NOACCESS",	ERROR_NOACCESS,
L"ERROR_SWAPERROR",	ERROR_SWAPERROR,
L"ERROR_STACK_OVERFLOW",	ERROR_STACK_OVERFLOW,
L"ERROR_INVALID_MESSAGE",	ERROR_INVALID_MESSAGE,
L"ERROR_CAN_NOT_COMPLETE",	ERROR_CAN_NOT_COMPLETE,
L"ERROR_INVALID_FLAGS",	ERROR_INVALID_FLAGS,
L"ERROR_UNRECOGNIZED_VOLUME",	ERROR_UNRECOGNIZED_VOLUME,
L"ERROR_FILE_INVALID",	ERROR_FILE_INVALID,
L"ERROR_FULLSCREEN_MODE",	ERROR_FULLSCREEN_MODE,
L"ERROR_NO_TOKEN",	ERROR_NO_TOKEN,
L"ERROR_BADDB",	ERROR_BADDB,
L"ERROR_BADKEY",	ERROR_BADKEY,
L"ERROR_CANTOPEN",	ERROR_CANTOPEN,
L"ERROR_CANTREAD",	ERROR_CANTREAD,
L"ERROR_CANTWRITE",	ERROR_CANTWRITE,
L"ERROR_REGISTRY_RECOVERED",	ERROR_REGISTRY_RECOVERED,
L"ERROR_REGISTRY_CORRUPT",	ERROR_REGISTRY_CORRUPT,
L"ERROR_REGISTRY_IO_FAILED",	ERROR_REGISTRY_IO_FAILED,
L"ERROR_NOT_REGISTRY_FILE",	ERROR_NOT_REGISTRY_FILE,
L"ERROR_KEY_DELETED",	ERROR_KEY_DELETED,
L"ERROR_NO_LOG_SPACE",	ERROR_NO_LOG_SPACE,
L"ERROR_KEY_HAS_CHILDREN",	ERROR_KEY_HAS_CHILDREN,
L"ERROR_CHILD_MUST_BE_VOLATILE",	ERROR_CHILD_MUST_BE_VOLATILE,
L"ERROR_NOTIFY_ENUM_DIR",	ERROR_NOTIFY_ENUM_DIR,
L"ERROR_DEPENDENT_SERVICES_RUNNING",	ERROR_DEPENDENT_SERVICES_RUNNING,
L"ERROR_INVALID_SERVICE_CONTROL",	ERROR_INVALID_SERVICE_CONTROL,
L"ERROR_SERVICE_REQUEST_TIMEOUT",	ERROR_SERVICE_REQUEST_TIMEOUT,
L"ERROR_SERVICE_NO_THREAD",	ERROR_SERVICE_NO_THREAD,
L"ERROR_SERVICE_DATABASE_LOCKED",	ERROR_SERVICE_DATABASE_LOCKED,
L"ERROR_SERVICE_ALREADY_RUNNING",	ERROR_SERVICE_ALREADY_RUNNING,
L"ERROR_INVALID_SERVICE_ACCOUNT",	ERROR_INVALID_SERVICE_ACCOUNT,
L"ERROR_SERVICE_DISABLED",	ERROR_SERVICE_DISABLED,
L"ERROR_CIRCULAR_DEPENDENCY",	ERROR_CIRCULAR_DEPENDENCY,
L"ERROR_SERVICE_DOES_NOT_EXIST",	ERROR_SERVICE_DOES_NOT_EXIST,
L"ERROR_SERVICE_CANNOT_ACCEPT_CTRL",	ERROR_SERVICE_CANNOT_ACCEPT_CTRL,
L"ERROR_SERVICE_NOT_ACTIVE",	ERROR_SERVICE_NOT_ACTIVE,
L"ERROR_FAILED_SERVICE_CONTROLLER_CONNECT",	ERROR_FAILED_SERVICE_CONTROLLER_CONNECT,
L"ERROR_EXCEPTION_IN_SERVICE",	ERROR_EXCEPTION_IN_SERVICE,
L"ERROR_DATABASE_DOES_NOT_EXIST",	ERROR_DATABASE_DOES_NOT_EXIST,
L"ERROR_SERVICE_SPECIFIC_ERROR",	ERROR_SERVICE_SPECIFIC_ERROR,
L"ERROR_PROCESS_ABORTED",	ERROR_PROCESS_ABORTED,
L"ERROR_SERVICE_DEPENDENCY_FAIL",	ERROR_SERVICE_DEPENDENCY_FAIL,
L"ERROR_SERVICE_LOGON_FAILED",	ERROR_SERVICE_LOGON_FAILED,
L"ERROR_SERVICE_START_HANG",	ERROR_SERVICE_START_HANG,
L"ERROR_INVALID_SERVICE_LOCK",	ERROR_INVALID_SERVICE_LOCK,
L"ERROR_SERVICE_MARKED_FOR_DELETE",	ERROR_SERVICE_MARKED_FOR_DELETE,
L"ERROR_SERVICE_EXISTS",	ERROR_SERVICE_EXISTS,
L"ERROR_ALREADY_RUNNING_LKG",	ERROR_ALREADY_RUNNING_LKG,
L"ERROR_SERVICE_DEPENDENCY_DELETED",	ERROR_SERVICE_DEPENDENCY_DELETED,
L"ERROR_BOOT_ALREADY_ACCEPTED",	ERROR_BOOT_ALREADY_ACCEPTED,
L"ERROR_SERVICE_NEVER_STARTED",	ERROR_SERVICE_NEVER_STARTED,
L"ERROR_DUPLICATE_SERVICE_NAME",	ERROR_DUPLICATE_SERVICE_NAME,
L"ERROR_DIFFERENT_SERVICE_ACCOUNT",	ERROR_DIFFERENT_SERVICE_ACCOUNT,
L"ERROR_CANNOT_DETECT_DRIVER_FAILURE",	ERROR_CANNOT_DETECT_DRIVER_FAILURE,
L"ERROR_CANNOT_DETECT_PROCESS_ABORT",	ERROR_CANNOT_DETECT_PROCESS_ABORT,
L"ERROR_NO_RECOVERY_PROGRAM",	ERROR_NO_RECOVERY_PROGRAM,
L"ERROR_END_OF_MEDIA",	ERROR_END_OF_MEDIA,
L"ERROR_FILEMARK_DETECTED",	ERROR_FILEMARK_DETECTED,
L"ERROR_BEGINNING_OF_MEDIA",	ERROR_BEGINNING_OF_MEDIA,
L"ERROR_SETMARK_DETECTED",	ERROR_SETMARK_DETECTED,
L"ERROR_NO_DATA_DETECTED",	ERROR_NO_DATA_DETECTED,
L"ERROR_PARTITION_FAILURE",	ERROR_PARTITION_FAILURE,
L"ERROR_INVALID_BLOCK_LENGTH",	ERROR_INVALID_BLOCK_LENGTH,
L"ERROR_DEVICE_NOT_PARTITIONED",	ERROR_DEVICE_NOT_PARTITIONED,
L"ERROR_UNABLE_TO_LOCK_MEDIA",	ERROR_UNABLE_TO_LOCK_MEDIA,
L"ERROR_UNABLE_TO_UNLOAD_MEDIA",	ERROR_UNABLE_TO_UNLOAD_MEDIA,
L"ERROR_MEDIA_CHANGED",	ERROR_MEDIA_CHANGED,
L"ERROR_BUS_RESET",	ERROR_BUS_RESET,
L"ERROR_NO_MEDIA_IN_DRIVE",	ERROR_NO_MEDIA_IN_DRIVE,
L"ERROR_NO_UNICODE_TRANSLATION",	ERROR_NO_UNICODE_TRANSLATION,
L"ERROR_DLL_INIT_FAILED",	ERROR_DLL_INIT_FAILED,
L"ERROR_SHUTDOWN_IN_PROGRESS",	ERROR_SHUTDOWN_IN_PROGRESS,
L"ERROR_NO_SHUTDOWN_IN_PROGRESS",	ERROR_NO_SHUTDOWN_IN_PROGRESS,
L"ERROR_IO_DEVICE",	ERROR_IO_DEVICE,
L"ERROR_SERIAL_NO_DEVICE",	ERROR_SERIAL_NO_DEVICE,
L"ERROR_IRQ_BUSY",	ERROR_IRQ_BUSY,
L"ERROR_MORE_WRITES",	ERROR_MORE_WRITES,
L"ERROR_COUNTER_TIMEOUT",	ERROR_COUNTER_TIMEOUT,
L"ERROR_FLOPPY_ID_MARK_NOT_FOUND",	ERROR_FLOPPY_ID_MARK_NOT_FOUND,
L"ERROR_FLOPPY_WRONG_CYLINDER",	ERROR_FLOPPY_WRONG_CYLINDER,
L"ERROR_FLOPPY_UNKNOWN_ERROR",	ERROR_FLOPPY_UNKNOWN_ERROR,
L"ERROR_FLOPPY_BAD_REGISTERS",	ERROR_FLOPPY_BAD_REGISTERS,
L"ERROR_DISK_RECALIBRATE_FAILED",	ERROR_DISK_RECALIBRATE_FAILED,
L"ERROR_DISK_OPERATION_FAILED",	ERROR_DISK_OPERATION_FAILED,
L"ERROR_DISK_RESET_FAILED",	ERROR_DISK_RESET_FAILED,
L"ERROR_EOM_OVERFLOW",	ERROR_EOM_OVERFLOW,
L"ERROR_NOT_ENOUGH_SERVER_MEMORY",	ERROR_NOT_ENOUGH_SERVER_MEMORY,
L"ERROR_POSSIBLE_DEADLOCK",	ERROR_POSSIBLE_DEADLOCK,
L"ERROR_MAPPED_ALIGNMENT",	ERROR_MAPPED_ALIGNMENT,
L"ERROR_SET_POWER_STATE_VETOED",	ERROR_SET_POWER_STATE_VETOED,
L"ERROR_SET_POWER_STATE_FAILED",	ERROR_SET_POWER_STATE_FAILED,
L"ERROR_TOO_MANY_LINKS",	ERROR_TOO_MANY_LINKS,
L"ERROR_OLD_WIN_VERSION",	ERROR_OLD_WIN_VERSION,
L"ERROR_APP_WRONG_OS",	ERROR_APP_WRONG_OS,
L"ERROR_SINGLE_INSTANCE_APP",	ERROR_SINGLE_INSTANCE_APP,
L"ERROR_RMODE_APP",	ERROR_RMODE_APP,
L"ERROR_INVALID_DLL",	ERROR_INVALID_DLL,
L"ERROR_NO_ASSOCIATION",	ERROR_NO_ASSOCIATION,
L"ERROR_DDE_FAIL",	ERROR_DDE_FAIL,
L"ERROR_DLL_NOT_FOUND",	ERROR_DLL_NOT_FOUND,
L"ERROR_NO_MORE_USER_HANDLES",	ERROR_NO_MORE_USER_HANDLES,
L"ERROR_MESSAGE_SYNC_ONLY",	ERROR_MESSAGE_SYNC_ONLY,
L"ERROR_SOURCE_ELEMENT_EMPTY",	ERROR_SOURCE_ELEMENT_EMPTY,
L"ERROR_DESTINATION_ELEMENT_FULL",	ERROR_DESTINATION_ELEMENT_FULL,
L"ERROR_ILLEGAL_ELEMENT_ADDRESS",	ERROR_ILLEGAL_ELEMENT_ADDRESS,
L"ERROR_MAGAZINE_NOT_PRESENT",	ERROR_MAGAZINE_NOT_PRESENT,
L"ERROR_DEVICE_REINITIALIZATION_NEEDED",	ERROR_DEVICE_REINITIALIZATION_NEEDED,
L"ERROR_DEVICE_REQUIRES_CLEANING",	ERROR_DEVICE_REQUIRES_CLEANING,
L"ERROR_DEVICE_DOOR_OPEN",	ERROR_DEVICE_DOOR_OPEN,
L"ERROR_DEVICE_NOT_CONNECTED",	ERROR_DEVICE_NOT_CONNECTED,
L"ERROR_NOT_FOUND",	ERROR_NOT_FOUND,
L"ERROR_NO_MATCH",	ERROR_NO_MATCH,
L"ERROR_SET_NOT_FOUND",	ERROR_SET_NOT_FOUND,
L"ERROR_POINT_NOT_FOUND",	ERROR_POINT_NOT_FOUND,
L"ERROR_NO_TRACKING_SERVICE",	ERROR_NO_TRACKING_SERVICE,
L"ERROR_NO_VOLUME_ID",	ERROR_NO_VOLUME_ID,
L"ERROR_CONNECTED_OTHER_PASSWORD",	ERROR_CONNECTED_OTHER_PASSWORD,
L"ERROR_BAD_USERNAME",	ERROR_BAD_USERNAME,
L"ERROR_NOT_CONNECTED",	ERROR_NOT_CONNECTED,
L"ERROR_OPEN_FILES",	ERROR_OPEN_FILES,
L"ERROR_ACTIVE_CONNECTIONS",	ERROR_ACTIVE_CONNECTIONS,
L"ERROR_DEVICE_IN_USE",	ERROR_DEVICE_IN_USE,
L"ERROR_BAD_DEVICE",	ERROR_BAD_DEVICE,
L"ERROR_CONNECTION_UNAVAIL",	ERROR_CONNECTION_UNAVAIL,
L"ERROR_DEVICE_ALREADY_REMEMBERED",	ERROR_DEVICE_ALREADY_REMEMBERED,
L"ERROR_NO_NET_OR_BAD_PATH",	ERROR_NO_NET_OR_BAD_PATH,
L"ERROR_BAD_PROVIDER",	ERROR_BAD_PROVIDER,
L"ERROR_CANNOT_OPEN_PROFILE",	ERROR_CANNOT_OPEN_PROFILE,
L"ERROR_BAD_PROFILE",	ERROR_BAD_PROFILE,
L"ERROR_NOT_CONTAINER",	ERROR_NOT_CONTAINER,
L"ERROR_EXTENDED_ERROR",	ERROR_EXTENDED_ERROR,
L"ERROR_INVALID_GROUPNAME",	ERROR_INVALID_GROUPNAME,
L"ERROR_INVALID_COMPUTERNAME",	ERROR_INVALID_COMPUTERNAME,
L"ERROR_INVALID_EVENTNAME",	ERROR_INVALID_EVENTNAME,
L"ERROR_INVALID_DOMAINNAME",	ERROR_INVALID_DOMAINNAME,
L"ERROR_INVALID_SERVICENAME",	ERROR_INVALID_SERVICENAME,
L"ERROR_INVALID_NETNAME",	ERROR_INVALID_NETNAME,
L"ERROR_INVALID_SHARENAME",	ERROR_INVALID_SHARENAME,
L"ERROR_INVALID_PASSWORDNAME",	ERROR_INVALID_PASSWORDNAME,
L"ERROR_INVALID_MESSAGENAME",	ERROR_INVALID_MESSAGENAME,
L"ERROR_INVALID_MESSAGEDEST",	ERROR_INVALID_MESSAGEDEST,
L"ERROR_SESSION_CREDENTIAL_CONFLICT",	ERROR_SESSION_CREDENTIAL_CONFLICT,
L"ERROR_REMOTE_SESSION_LIMIT_EXCEEDED",	ERROR_REMOTE_SESSION_LIMIT_EXCEEDED,
L"ERROR_DUP_DOMAINNAME",	ERROR_DUP_DOMAINNAME,
L"ERROR_NO_NETWORK",	ERROR_NO_NETWORK,
L"ERROR_CANCELLED",	ERROR_CANCELLED,
L"ERROR_USER_MAPPED_FILE",	ERROR_USER_MAPPED_FILE,
L"ERROR_CONNECTION_REFUSED",	ERROR_CONNECTION_REFUSED,
L"ERROR_GRACEFUL_DISCONNECT",	ERROR_GRACEFUL_DISCONNECT,
L"ERROR_ADDRESS_ALREADY_ASSOCIATED",	ERROR_ADDRESS_ALREADY_ASSOCIATED,
L"ERROR_ADDRESS_NOT_ASSOCIATED",	ERROR_ADDRESS_NOT_ASSOCIATED,
L"ERROR_CONNECTION_INVALID",	ERROR_CONNECTION_INVALID,
L"ERROR_CONNECTION_ACTIVE",	ERROR_CONNECTION_ACTIVE,
L"ERROR_NETWORK_UNREACHABLE",	ERROR_NETWORK_UNREACHABLE,
L"ERROR_HOST_UNREACHABLE",	ERROR_HOST_UNREACHABLE,
L"ERROR_PROTOCOL_UNREACHABLE",	ERROR_PROTOCOL_UNREACHABLE,
L"ERROR_PORT_UNREACHABLE",	ERROR_PORT_UNREACHABLE,
L"ERROR_REQUEST_ABORTED",	ERROR_REQUEST_ABORTED,
L"ERROR_CONNECTION_ABORTED",	ERROR_CONNECTION_ABORTED,
L"ERROR_RETRY",	ERROR_RETRY,
L"ERROR_CONNECTION_COUNT_LIMIT",	ERROR_CONNECTION_COUNT_LIMIT,
L"ERROR_LOGIN_TIME_RESTRICTION",	ERROR_LOGIN_TIME_RESTRICTION,
L"ERROR_LOGIN_WKSTA_RESTRICTION",	ERROR_LOGIN_WKSTA_RESTRICTION,
L"ERROR_INCORRECT_ADDRESS",	ERROR_INCORRECT_ADDRESS,
L"ERROR_ALREADY_REGISTERED",	ERROR_ALREADY_REGISTERED,
L"ERROR_SERVICE_NOT_FOUND",	ERROR_SERVICE_NOT_FOUND,
L"ERROR_NOT_AUTHENTICATED",	ERROR_NOT_AUTHENTICATED,
L"ERROR_NOT_LOGGED_ON",	ERROR_NOT_LOGGED_ON,
L"ERROR_CONTINUE",	ERROR_CONTINUE,
L"ERROR_ALREADY_INITIALIZED",	ERROR_ALREADY_INITIALIZED,
L"ERROR_NO_MORE_DEVICES",	ERROR_NO_MORE_DEVICES,
L"ERROR_NO_SUCH_SITE",	ERROR_NO_SUCH_SITE,
L"ERROR_DOMAIN_CONTROLLER_EXISTS",	ERROR_DOMAIN_CONTROLLER_EXISTS,
L"ERROR_DS_NOT_INSTALLED",	ERROR_DS_NOT_INSTALLED,
L"ERROR_NOT_ALL_ASSIGNED",	ERROR_NOT_ALL_ASSIGNED,
L"ERROR_SOME_NOT_MAPPED",	ERROR_SOME_NOT_MAPPED,
L"ERROR_NO_QUOTAS_FOR_ACCOUNT",	ERROR_NO_QUOTAS_FOR_ACCOUNT,
L"ERROR_LOCAL_USER_SESSION_KEY",	ERROR_LOCAL_USER_SESSION_KEY,
L"ERROR_NULL_LM_PASSWORD",	ERROR_NULL_LM_PASSWORD,
L"ERROR_UNKNOWN_REVISION",	ERROR_UNKNOWN_REVISION,
L"ERROR_REVISION_MISMATCH",	ERROR_REVISION_MISMATCH,
L"ERROR_INVALID_OWNER",	ERROR_INVALID_OWNER,
L"ERROR_INVALID_PRIMARY_GROUP",	ERROR_INVALID_PRIMARY_GROUP,
L"ERROR_NO_IMPERSONATION_TOKEN",	ERROR_NO_IMPERSONATION_TOKEN,
L"ERROR_CANT_DISABLE_MANDATORY",	ERROR_CANT_DISABLE_MANDATORY,
L"ERROR_NO_LOGON_SERVERS",	ERROR_NO_LOGON_SERVERS,
L"ERROR_NO_SUCH_LOGON_SESSION",	ERROR_NO_SUCH_LOGON_SESSION,
L"ERROR_NO_SUCH_PRIVILEGE",	ERROR_NO_SUCH_PRIVILEGE,
L"ERROR_PRIVILEGE_NOT_HELD",	ERROR_PRIVILEGE_NOT_HELD,
L"ERROR_INVALID_ACCOUNT_NAME",	ERROR_INVALID_ACCOUNT_NAME,
L"ERROR_USER_EXISTS",	ERROR_USER_EXISTS,
L"ERROR_NO_SUCH_USER",	ERROR_NO_SUCH_USER,
L"ERROR_GROUP_EXISTS",	ERROR_GROUP_EXISTS,
L"ERROR_NO_SUCH_GROUP",	ERROR_NO_SUCH_GROUP,
L"ERROR_MEMBER_IN_GROUP",	ERROR_MEMBER_IN_GROUP,
L"ERROR_MEMBER_NOT_IN_GROUP",	ERROR_MEMBER_NOT_IN_GROUP,
L"ERROR_LAST_ADMIN",	ERROR_LAST_ADMIN,
L"ERROR_WRONG_PASSWORD",	ERROR_WRONG_PASSWORD,
L"ERROR_ILL_FORMED_PASSWORD",	ERROR_ILL_FORMED_PASSWORD,
L"ERROR_PASSWORD_RESTRICTION",	ERROR_PASSWORD_RESTRICTION,
L"ERROR_LOGON_FAILURE",	ERROR_LOGON_FAILURE,
L"ERROR_ACCOUNT_RESTRICTION",	ERROR_ACCOUNT_RESTRICTION,
L"ERROR_INVALID_LOGON_HOURS",	ERROR_INVALID_LOGON_HOURS,
L"ERROR_INVALID_WORKSTATION",	ERROR_INVALID_WORKSTATION,
L"ERROR_PASSWORD_EXPIRED",	ERROR_PASSWORD_EXPIRED,
L"ERROR_ACCOUNT_DISABLED",	ERROR_ACCOUNT_DISABLED,
L"ERROR_NONE_MAPPED",	ERROR_NONE_MAPPED,
L"ERROR_TOO_MANY_LUIDS_REQUESTED",	ERROR_TOO_MANY_LUIDS_REQUESTED,
L"ERROR_LUIDS_EXHAUSTED",	ERROR_LUIDS_EXHAUSTED,
L"ERROR_INVALID_SUB_AUTHORITY",	ERROR_INVALID_SUB_AUTHORITY,
L"ERROR_INVALID_ACL",	ERROR_INVALID_ACL,
L"ERROR_INVALID_SID",	ERROR_INVALID_SID,
L"ERROR_INVALID_SECURITY_DESCR",	ERROR_INVALID_SECURITY_DESCR,
L"ERROR_BAD_INHERITANCE_ACL",	ERROR_BAD_INHERITANCE_ACL,
L"ERROR_SERVER_DISABLED",	ERROR_SERVER_DISABLED,
L"ERROR_SERVER_NOT_DISABLED",	ERROR_SERVER_NOT_DISABLED,
L"ERROR_INVALID_ID_AUTHORITY",	ERROR_INVALID_ID_AUTHORITY,
L"ERROR_ALLOTTED_SPACE_EXCEEDED",	ERROR_ALLOTTED_SPACE_EXCEEDED,
L"ERROR_INVALID_GROUP_ATTRIBUTES",	ERROR_INVALID_GROUP_ATTRIBUTES,
L"ERROR_BAD_IMPERSONATION_LEVEL",	ERROR_BAD_IMPERSONATION_LEVEL,
L"ERROR_CANT_OPEN_ANONYMOUS",	ERROR_CANT_OPEN_ANONYMOUS,
L"ERROR_BAD_VALIDATION_CLASS",	ERROR_BAD_VALIDATION_CLASS,
L"ERROR_BAD_TOKEN_TYPE",	ERROR_BAD_TOKEN_TYPE,
L"ERROR_NO_SECURITY_ON_OBJECT",	ERROR_NO_SECURITY_ON_OBJECT,
L"ERROR_CANT_ACCESS_DOMAIN_INFO",	ERROR_CANT_ACCESS_DOMAIN_INFO,
L"ERROR_INVALID_SERVER_STATE",	ERROR_INVALID_SERVER_STATE,
L"ERROR_INVALID_DOMAIN_STATE",	ERROR_INVALID_DOMAIN_STATE,
L"ERROR_INVALID_DOMAIN_ROLE",	ERROR_INVALID_DOMAIN_ROLE,
L"ERROR_NO_SUCH_DOMAIN",	ERROR_NO_SUCH_DOMAIN,
L"ERROR_DOMAIN_EXISTS",	ERROR_DOMAIN_EXISTS,
L"ERROR_DOMAIN_LIMIT_EXCEEDED",	ERROR_DOMAIN_LIMIT_EXCEEDED,
L"ERROR_INTERNAL_DB_CORRUPTION",	ERROR_INTERNAL_DB_CORRUPTION,
L"ERROR_INTERNAL_ERROR",	ERROR_INTERNAL_ERROR,
L"ERROR_GENERIC_NOT_MAPPED",	ERROR_GENERIC_NOT_MAPPED,
L"ERROR_BAD_DESCRIPTOR_FORMAT",	ERROR_BAD_DESCRIPTOR_FORMAT,
L"ERROR_NOT_LOGON_PROCESS",	ERROR_NOT_LOGON_PROCESS,
L"ERROR_LOGON_SESSION_EXISTS",	ERROR_LOGON_SESSION_EXISTS,
L"ERROR_NO_SUCH_PACKAGE",	ERROR_NO_SUCH_PACKAGE,
L"ERROR_BAD_LOGON_SESSION_STATE",	ERROR_BAD_LOGON_SESSION_STATE,
L"ERROR_LOGON_SESSION_COLLISION",	ERROR_LOGON_SESSION_COLLISION,
L"ERROR_INVALID_LOGON_TYPE",	ERROR_INVALID_LOGON_TYPE,
L"ERROR_CANNOT_IMPERSONATE",	ERROR_CANNOT_IMPERSONATE,
L"ERROR_RXACT_INVALID_STATE",	ERROR_RXACT_INVALID_STATE,
L"ERROR_RXACT_COMMIT_FAILURE",	ERROR_RXACT_COMMIT_FAILURE,
L"ERROR_SPECIAL_ACCOUNT",	ERROR_SPECIAL_ACCOUNT,
L"ERROR_SPECIAL_GROUP",	ERROR_SPECIAL_GROUP,
L"ERROR_SPECIAL_USER",	ERROR_SPECIAL_USER,
L"ERROR_MEMBERS_PRIMARY_GROUP",	ERROR_MEMBERS_PRIMARY_GROUP,
L"ERROR_TOKEN_ALREADY_IN_USE",	ERROR_TOKEN_ALREADY_IN_USE,
L"ERROR_NO_SUCH_ALIAS",	ERROR_NO_SUCH_ALIAS,
L"ERROR_MEMBER_NOT_IN_ALIAS",	ERROR_MEMBER_NOT_IN_ALIAS,
L"ERROR_MEMBER_IN_ALIAS",	ERROR_MEMBER_IN_ALIAS,
L"ERROR_ALIAS_EXISTS",	ERROR_ALIAS_EXISTS,
L"ERROR_LOGON_NOT_GRANTED",	ERROR_LOGON_NOT_GRANTED,
L"ERROR_TOO_MANY_SECRETS",	ERROR_TOO_MANY_SECRETS,
L"ERROR_SECRET_TOO_LONG",	ERROR_SECRET_TOO_LONG,
L"ERROR_INTERNAL_DB_ERROR",	ERROR_INTERNAL_DB_ERROR,
L"ERROR_TOO_MANY_CONTEXT_IDS",	ERROR_TOO_MANY_CONTEXT_IDS,
L"ERROR_LOGON_TYPE_NOT_GRANTED",	ERROR_LOGON_TYPE_NOT_GRANTED,
L"ERROR_NT_CROSS_ENCRYPTION_REQUIRED",	ERROR_NT_CROSS_ENCRYPTION_REQUIRED,
L"ERROR_NO_SUCH_MEMBER",	ERROR_NO_SUCH_MEMBER,
L"ERROR_INVALID_MEMBER",	ERROR_INVALID_MEMBER,
L"ERROR_TOO_MANY_SIDS",	ERROR_TOO_MANY_SIDS,
L"ERROR_LM_CROSS_ENCRYPTION_REQUIRED",	ERROR_LM_CROSS_ENCRYPTION_REQUIRED,
L"ERROR_NO_INHERITANCE",	ERROR_NO_INHERITANCE,
L"ERROR_FILE_CORRUPT",	ERROR_FILE_CORRUPT,
L"ERROR_DISK_CORRUPT",	ERROR_DISK_CORRUPT,
L"ERROR_NO_USER_SESSION_KEY",	ERROR_NO_USER_SESSION_KEY,
L"ERROR_LICENSE_QUOTA_EXCEEDED",	ERROR_LICENSE_QUOTA_EXCEEDED,
L"ERROR_INVALID_WINDOW_HANDLE",	ERROR_INVALID_WINDOW_HANDLE,
L"ERROR_INVALID_MENU_HANDLE",	ERROR_INVALID_MENU_HANDLE,
L"ERROR_INVALID_CURSOR_HANDLE",	ERROR_INVALID_CURSOR_HANDLE,
L"ERROR_INVALID_ACCEL_HANDLE",	ERROR_INVALID_ACCEL_HANDLE,
L"ERROR_INVALID_HOOK_HANDLE",	ERROR_INVALID_HOOK_HANDLE,
L"ERROR_INVALID_DWP_HANDLE",	ERROR_INVALID_DWP_HANDLE,
L"ERROR_TLW_WITH_WSCHILD",	ERROR_TLW_WITH_WSCHILD,
L"ERROR_CANNOT_FIND_WND_CLASS",	ERROR_CANNOT_FIND_WND_CLASS,
L"ERROR_WINDOW_OF_OTHER_THREAD",	ERROR_WINDOW_OF_OTHER_THREAD,
L"ERROR_HOTKEY_ALREADY_REGISTERED",	ERROR_HOTKEY_ALREADY_REGISTERED,
L"ERROR_CLASS_ALREADY_EXISTS",	ERROR_CLASS_ALREADY_EXISTS,
L"ERROR_CLASS_DOES_NOT_EXIST",	ERROR_CLASS_DOES_NOT_EXIST,
L"ERROR_CLASS_HAS_WINDOWS",	ERROR_CLASS_HAS_WINDOWS,
L"ERROR_INVALID_INDEX",	ERROR_INVALID_INDEX,
L"ERROR_INVALID_ICON_HANDLE",	ERROR_INVALID_ICON_HANDLE,
L"ERROR_PRIVATE_DIALOG_INDEX",	ERROR_PRIVATE_DIALOG_INDEX,
L"ERROR_LISTBOX_ID_NOT_FOUND",	ERROR_LISTBOX_ID_NOT_FOUND,
L"ERROR_NO_WILDCARD_CHARACTERS",	ERROR_NO_WILDCARD_CHARACTERS,
L"ERROR_CLIPBOARD_NOT_OPEN",	ERROR_CLIPBOARD_NOT_OPEN,
L"ERROR_HOTKEY_NOT_REGISTERED",	ERROR_HOTKEY_NOT_REGISTERED,
L"ERROR_WINDOW_NOT_DIALOG",	ERROR_WINDOW_NOT_DIALOG,
L"ERROR_CONTROL_ID_NOT_FOUND",	ERROR_CONTROL_ID_NOT_FOUND,
L"ERROR_INVALID_COMBOBOX_MESSAGE",	ERROR_INVALID_COMBOBOX_MESSAGE,
L"ERROR_WINDOW_NOT_COMBOBOX",	ERROR_WINDOW_NOT_COMBOBOX,
L"ERROR_INVALID_EDIT_HEIGHT",	ERROR_INVALID_EDIT_HEIGHT,
L"ERROR_DC_NOT_FOUND",	ERROR_DC_NOT_FOUND,
L"ERROR_INVALID_HOOK_FILTER",	ERROR_INVALID_HOOK_FILTER,
L"ERROR_INVALID_FILTER_PROC",	ERROR_INVALID_FILTER_PROC,
L"ERROR_HOOK_NEEDS_HMOD",	ERROR_HOOK_NEEDS_HMOD,
L"ERROR_GLOBAL_ONLY_HOOK",	ERROR_GLOBAL_ONLY_HOOK,
L"ERROR_JOURNAL_HOOK_SET",	ERROR_JOURNAL_HOOK_SET,
L"ERROR_HOOK_NOT_INSTALLED",	ERROR_HOOK_NOT_INSTALLED,
L"ERROR_INVALID_LB_MESSAGE",	ERROR_INVALID_LB_MESSAGE,
L"ERROR_SETCOUNT_ON_BAD_LB",	ERROR_SETCOUNT_ON_BAD_LB,
L"ERROR_LB_WITHOUT_TABSTOPS",	ERROR_LB_WITHOUT_TABSTOPS,
L"ERROR_DESTROY_OBJECT_OF_OTHER_THREAD",	ERROR_DESTROY_OBJECT_OF_OTHER_THREAD,
L"ERROR_CHILD_WINDOW_MENU",	ERROR_CHILD_WINDOW_MENU,
L"ERROR_NO_SYSTEM_MENU",	ERROR_NO_SYSTEM_MENU,
L"ERROR_INVALID_MSGBOX_STYLE",	ERROR_INVALID_MSGBOX_STYLE,
L"ERROR_INVALID_SPI_VALUE",	ERROR_INVALID_SPI_VALUE,
L"ERROR_SCREEN_ALREADY_LOCKED",	ERROR_SCREEN_ALREADY_LOCKED,
L"ERROR_HWNDS_HAVE_DIFF_PARENT",	ERROR_HWNDS_HAVE_DIFF_PARENT,
L"ERROR_NOT_CHILD_WINDOW",	ERROR_NOT_CHILD_WINDOW,
L"ERROR_INVALID_GW_COMMAND",	ERROR_INVALID_GW_COMMAND,
L"ERROR_INVALID_THREAD_ID",	ERROR_INVALID_THREAD_ID,
L"ERROR_NON_MDICHILD_WINDOW",	ERROR_NON_MDICHILD_WINDOW,
L"ERROR_POPUP_ALREADY_ACTIVE",	ERROR_POPUP_ALREADY_ACTIVE,
L"ERROR_NO_SCROLLBARS",	ERROR_NO_SCROLLBARS,
L"ERROR_INVALID_SCROLLBAR_RANGE",	ERROR_INVALID_SCROLLBAR_RANGE,
L"ERROR_INVALID_SHOWWIN_COMMAND",	ERROR_INVALID_SHOWWIN_COMMAND,
L"ERROR_NO_SYSTEM_RESOURCES",	ERROR_NO_SYSTEM_RESOURCES,
L"ERROR_NONPAGED_SYSTEM_RESOURCES",	ERROR_NONPAGED_SYSTEM_RESOURCES,
L"ERROR_PAGED_SYSTEM_RESOURCES",	ERROR_PAGED_SYSTEM_RESOURCES,
L"ERROR_WORKING_SET_QUOTA",	ERROR_WORKING_SET_QUOTA,
L"ERROR_PAGEFILE_QUOTA",	ERROR_PAGEFILE_QUOTA,
L"ERROR_COMMITMENT_LIMIT",	ERROR_COMMITMENT_LIMIT,
L"ERROR_MENU_ITEM_NOT_FOUND",	ERROR_MENU_ITEM_NOT_FOUND,
L"ERROR_INVALID_KEYBOARD_HANDLE",	ERROR_INVALID_KEYBOARD_HANDLE,
L"ERROR_HOOK_TYPE_NOT_ALLOWED",	ERROR_HOOK_TYPE_NOT_ALLOWED,
L"ERROR_REQUIRES_INTERACTIVE_WINDOWSTATION",	ERROR_REQUIRES_INTERACTIVE_WINDOWSTATION,
L"ERROR_TIMEOUT",	ERROR_TIMEOUT,
L"ERROR_INVALID_MONITOR_HANDLE",	ERROR_INVALID_MONITOR_HANDLE,
L"ERROR_EVENTLOG_FILE_CORRUPT",	ERROR_EVENTLOG_FILE_CORRUPT,
L"ERROR_EVENTLOG_CANT_START",	ERROR_EVENTLOG_CANT_START,
L"ERROR_LOG_FILE_FULL",	ERROR_LOG_FILE_FULL,
L"ERROR_EVENTLOG_FILE_CHANGED",	ERROR_EVENTLOG_FILE_CHANGED,
//"ERROR_INSTALL_SERVICE",	ERROR_INSTALL_SERVICE,
L"ERROR_INSTALL_USEREXIT",	ERROR_INSTALL_USEREXIT,
L"ERROR_INSTALL_FAILURE",	ERROR_INSTALL_FAILURE,
L"ERROR_INSTALL_SUSPEND",	ERROR_INSTALL_SUSPEND,
L"ERROR_UNKNOWN_PRODUCT",	ERROR_UNKNOWN_PRODUCT,
L"ERROR_UNKNOWN_FEATURE",	ERROR_UNKNOWN_FEATURE,
L"ERROR_UNKNOWN_COMPONENT",	ERROR_UNKNOWN_COMPONENT,
L"ERROR_UNKNOWN_PROPERTY",	ERROR_UNKNOWN_PROPERTY,
L"ERROR_INVALID_HANDLE_STATE",	ERROR_INVALID_HANDLE_STATE,
L"ERROR_BAD_CONFIGURATION",	ERROR_BAD_CONFIGURATION,
L"ERROR_INDEX_ABSENT",	ERROR_INDEX_ABSENT,
L"ERROR_INSTALL_SOURCE_ABSENT",	ERROR_INSTALL_SOURCE_ABSENT,
//"ERROR_BAD_DATABASE_VERSION",	ERROR_BAD_DATABASE_VERSION,
L"ERROR_PRODUCT_UNINSTALLED",	ERROR_PRODUCT_UNINSTALLED,
L"ERROR_BAD_QUERY_SYNTAX",	ERROR_BAD_QUERY_SYNTAX,
L"ERROR_INVALID_FIELD",	ERROR_INVALID_FIELD,
L"ERROR_INVALID_USER_BUFFER",	ERROR_INVALID_USER_BUFFER,
L"ERROR_UNRECOGNIZED_MEDIA",	ERROR_UNRECOGNIZED_MEDIA,
L"ERROR_NO_TRUST_LSA_SECRET",	ERROR_NO_TRUST_LSA_SECRET,
L"ERROR_NO_TRUST_SAM_ACCOUNT",	ERROR_NO_TRUST_SAM_ACCOUNT,
L"ERROR_TRUSTED_DOMAIN_FAILURE",	ERROR_TRUSTED_DOMAIN_FAILURE,
L"ERROR_TRUSTED_RELATIONSHIP_FAILURE",	ERROR_TRUSTED_RELATIONSHIP_FAILURE,
L"ERROR_TRUST_FAILURE",	ERROR_TRUST_FAILURE,
L"ERROR_NETLOGON_NOT_STARTED",	ERROR_NETLOGON_NOT_STARTED,
L"ERROR_ACCOUNT_EXPIRED",	ERROR_ACCOUNT_EXPIRED,
L"ERROR_REDIRECTOR_HAS_OPEN_HANDLES",	ERROR_REDIRECTOR_HAS_OPEN_HANDLES,
L"ERROR_PRINTER_DRIVER_ALREADY_INSTALLED",	ERROR_PRINTER_DRIVER_ALREADY_INSTALLED,
L"ERROR_UNKNOWN_PORT",	ERROR_UNKNOWN_PORT,
L"ERROR_UNKNOWN_PRINTER_DRIVER",	ERROR_UNKNOWN_PRINTER_DRIVER,
L"ERROR_UNKNOWN_PRINTPROCESSOR",	ERROR_UNKNOWN_PRINTPROCESSOR,
L"ERROR_INVALID_SEPARATOR_FILE",	ERROR_INVALID_SEPARATOR_FILE,
L"ERROR_INVALID_PRIORITY",	ERROR_INVALID_PRIORITY,
L"ERROR_INVALID_PRINTER_NAME",	ERROR_INVALID_PRINTER_NAME,
L"ERROR_PRINTER_ALREADY_EXISTS",	ERROR_PRINTER_ALREADY_EXISTS,
L"ERROR_INVALID_PRINTER_COMMAND",	ERROR_INVALID_PRINTER_COMMAND,
L"ERROR_INVALID_DATATYPE",	ERROR_INVALID_DATATYPE,
L"ERROR_INVALID_ENVIRONMENT",	ERROR_INVALID_ENVIRONMENT,
L"ERROR_NOLOGON_INTERDOMAIN_TRUST_ACCOUNT",	ERROR_NOLOGON_INTERDOMAIN_TRUST_ACCOUNT,
L"ERROR_NOLOGON_WORKSTATION_TRUST_ACCOUNT",	ERROR_NOLOGON_WORKSTATION_TRUST_ACCOUNT,
L"ERROR_NOLOGON_SERVER_TRUST_ACCOUNT",	ERROR_NOLOGON_SERVER_TRUST_ACCOUNT,
L"ERROR_DOMAIN_TRUST_INCONSISTENT",	ERROR_DOMAIN_TRUST_INCONSISTENT,
L"ERROR_SERVER_HAS_OPEN_HANDLES",	ERROR_SERVER_HAS_OPEN_HANDLES,
L"ERROR_RESOURCE_DATA_NOT_FOUND",	ERROR_RESOURCE_DATA_NOT_FOUND,
L"ERROR_RESOURCE_TYPE_NOT_FOUND",	ERROR_RESOURCE_TYPE_NOT_FOUND,
L"ERROR_RESOURCE_NAME_NOT_FOUND",	ERROR_RESOURCE_NAME_NOT_FOUND,
L"ERROR_RESOURCE_LANG_NOT_FOUND",	ERROR_RESOURCE_LANG_NOT_FOUND,
L"ERROR_NOT_ENOUGH_QUOTA",	ERROR_NOT_ENOUGH_QUOTA,
L"ERROR_INVALID_TIME",	ERROR_INVALID_TIME,
L"ERROR_INVALID_FORM_NAME",	ERROR_INVALID_FORM_NAME,
L"ERROR_INVALID_FORM_SIZE",	ERROR_INVALID_FORM_SIZE,
L"ERROR_ALREADY_WAITING",	ERROR_ALREADY_WAITING,
L"ERROR_PRINTER_DELETED",	ERROR_PRINTER_DELETED,
L"ERROR_INVALID_PRINTER_STATE",	ERROR_INVALID_PRINTER_STATE,
L"ERROR_PASSWORD_MUST_CHANGE",	ERROR_PASSWORD_MUST_CHANGE,
L"ERROR_DOMAIN_CONTROLLER_NOT_FOUND",	ERROR_DOMAIN_CONTROLLER_NOT_FOUND,
L"ERROR_ACCOUNT_LOCKED_OUT",	ERROR_ACCOUNT_LOCKED_OUT,
L"ERROR_NO_SITENAME",	ERROR_NO_SITENAME,
L"ERROR_CANT_ACCESS_FILE",	ERROR_CANT_ACCESS_FILE,
L"ERROR_CANT_RESOLVE_FILENAME",	ERROR_CANT_RESOLVE_FILENAME,
L"ERROR_DS_MEMBERSHIP_EVALUATED_LOCALLY",	ERROR_DS_MEMBERSHIP_EVALUATED_LOCALLY,
L"ERROR_DS_NO_ATTRIBUTE_OR_VALUE",	ERROR_DS_NO_ATTRIBUTE_OR_VALUE,
L"ERROR_DS_INVALID_ATTRIBUTE_SYNTAX",	ERROR_DS_INVALID_ATTRIBUTE_SYNTAX,
L"ERROR_DS_ATTRIBUTE_TYPE_UNDEFINED",	ERROR_DS_ATTRIBUTE_TYPE_UNDEFINED,
L"ERROR_DS_ATTRIBUTE_OR_VALUE_EXISTS",	ERROR_DS_ATTRIBUTE_OR_VALUE_EXISTS,
L"ERROR_DS_BUSY",	ERROR_DS_BUSY,
L"ERROR_DS_UNAVAILABLE",	ERROR_DS_UNAVAILABLE,
L"ERROR_DS_NO_RIDS_ALLOCATED",	ERROR_DS_NO_RIDS_ALLOCATED,
L"ERROR_DS_NO_MORE_RIDS",	ERROR_DS_NO_MORE_RIDS,
L"ERROR_DS_INCORRECT_ROLE_OWNER",	ERROR_DS_INCORRECT_ROLE_OWNER,
L"ERROR_DS_RIDMGR_INIT_ERROR",	ERROR_DS_RIDMGR_INIT_ERROR,
L"ERROR_DS_OBJ_CLASS_VIOLATION",	ERROR_DS_OBJ_CLASS_VIOLATION,
L"ERROR_DS_CANT_ON_NON_LEAF",	ERROR_DS_CANT_ON_NON_LEAF,
L"ERROR_DS_CANT_ON_RDN",	ERROR_DS_CANT_ON_RDN,
L"ERROR_DS_CANT_MOD_OBJ_CLASS",	ERROR_DS_CANT_MOD_OBJ_CLASS,
L"ERROR_DS_CROSS_DOM_MOVE_ERROR",	ERROR_DS_CROSS_DOM_MOVE_ERROR,
L"ERROR_DS_GC_NOT_AVAILABLE",	ERROR_DS_GC_NOT_AVAILABLE,
L"ERROR_NO_BROWSER_SERVERS_FOUND",	ERROR_NO_BROWSER_SERVERS_FOUND,
L"ERROR_INVALID_PIXEL_FORMAT",	ERROR_INVALID_PIXEL_FORMAT,
L"ERROR_BAD_DRIVER",	ERROR_BAD_DRIVER,
L"ERROR_INVALID_WINDOW_STYLE",	ERROR_INVALID_WINDOW_STYLE,
L"ERROR_METAFILE_NOT_SUPPORTED",	ERROR_METAFILE_NOT_SUPPORTED,
L"ERROR_TRANSFORM_NOT_SUPPORTED",	ERROR_TRANSFORM_NOT_SUPPORTED,
L"ERROR_CLIPPING_NOT_SUPPORTED",	ERROR_CLIPPING_NOT_SUPPORTED,
L"ERROR_INVALID_CMM",	ERROR_INVALID_CMM,
L"ERROR_INVALID_PROFILE",	ERROR_INVALID_PROFILE,
L"ERROR_TAG_NOT_FOUND",	ERROR_TAG_NOT_FOUND,
L"ERROR_TAG_NOT_PRESENT",	ERROR_TAG_NOT_PRESENT,
L"ERROR_DUPLICATE_TAG",	ERROR_DUPLICATE_TAG,
L"ERROR_PROFILE_NOT_ASSOCIATED_WITH_DEVICE",	ERROR_PROFILE_NOT_ASSOCIATED_WITH_DEVICE,
L"ERROR_PROFILE_NOT_FOUND",	ERROR_PROFILE_NOT_FOUND,
L"ERROR_INVALID_COLORSPACE",	ERROR_INVALID_COLORSPACE,
L"ERROR_ICM_NOT_ENABLED",	ERROR_ICM_NOT_ENABLED,
L"ERROR_DELETING_ICM_XFORM",	ERROR_DELETING_ICM_XFORM,
L"ERROR_INVALID_TRANSFORM",	ERROR_INVALID_TRANSFORM,
L"ERROR_UNKNOWN_PRINT_MONITOR",	ERROR_UNKNOWN_PRINT_MONITOR,
L"ERROR_PRINTER_DRIVER_IN_USE",	ERROR_PRINTER_DRIVER_IN_USE,
L"ERROR_SPOOL_FILE_NOT_FOUND",	ERROR_SPOOL_FILE_NOT_FOUND,
L"ERROR_SPL_NO_STARTDOC",	ERROR_SPL_NO_STARTDOC,
L"ERROR_SPL_NO_ADDJOB",	ERROR_SPL_NO_ADDJOB,
L"ERROR_PRINT_PROCESSOR_ALREADY_INSTALLED",	ERROR_PRINT_PROCESSOR_ALREADY_INSTALLED,
L"ERROR_PRINT_MONITOR_ALREADY_INSTALLED",	ERROR_PRINT_MONITOR_ALREADY_INSTALLED,
L"ERROR_INVALID_PRINT_MONITOR",	ERROR_INVALID_PRINT_MONITOR,
L"ERROR_PRINT_MONITOR_IN_USE",	ERROR_PRINT_MONITOR_IN_USE,
L"ERROR_PRINTER_HAS_JOBS_QUEUED",	ERROR_PRINTER_HAS_JOBS_QUEUED,
L"ERROR_SUCCESS_REBOOT_REQUIRED",	ERROR_SUCCESS_REBOOT_REQUIRED,
L"ERROR_SUCCESS_RESTART_REQUIRED",	ERROR_SUCCESS_RESTART_REQUIRED,
L"ERROR_WINS_INTERNAL",	ERROR_WINS_INTERNAL,
L"ERROR_CAN_NOT_DEL_LOCAL_WINS",	ERROR_CAN_NOT_DEL_LOCAL_WINS,
L"ERROR_STATIC_INIT",	ERROR_STATIC_INIT,
L"ERROR_INC_BACKUP",	ERROR_INC_BACKUP,
L"ERROR_FULL_BACKUP",	ERROR_FULL_BACKUP,
L"ERROR_REC_NON_EXISTENT",	ERROR_REC_NON_EXISTENT,
L"ERROR_RPL_NOT_ALLOWED",	ERROR_RPL_NOT_ALLOWED,
L"ERROR_DHCP_ADDRESS_CONFLICT",	ERROR_DHCP_ADDRESS_CONFLICT,
L"ERROR_WMI_GUID_NOT_FOUND",	ERROR_WMI_GUID_NOT_FOUND,
L"ERROR_WMI_INSTANCE_NOT_FOUND",	ERROR_WMI_INSTANCE_NOT_FOUND,
L"ERROR_WMI_ITEMID_NOT_FOUND",	ERROR_WMI_ITEMID_NOT_FOUND,
L"ERROR_WMI_TRY_AGAIN",	ERROR_WMI_TRY_AGAIN,
L"ERROR_WMI_DP_NOT_FOUND",	ERROR_WMI_DP_NOT_FOUND,
L"ERROR_WMI_UNRESOLVED_INSTANCE_REF",	ERROR_WMI_UNRESOLVED_INSTANCE_REF,
L"ERROR_WMI_ALREADY_ENABLED",	ERROR_WMI_ALREADY_ENABLED,
L"ERROR_WMI_GUID_DISCONNECTED",	ERROR_WMI_GUID_DISCONNECTED,
L"ERROR_WMI_SERVER_UNAVAILABLE",	ERROR_WMI_SERVER_UNAVAILABLE,
L"ERROR_WMI_DP_FAILED",	ERROR_WMI_DP_FAILED,
L"ERROR_WMI_INVALID_MOF",	ERROR_WMI_INVALID_MOF,
L"ERROR_WMI_INVALID_REGINFO",	ERROR_WMI_INVALID_REGINFO,
L"ERROR_INVALID_MEDIA",	ERROR_INVALID_MEDIA,
L"ERROR_INVALID_LIBRARY",	ERROR_INVALID_LIBRARY,
L"ERROR_INVALID_MEDIA_POOL",	ERROR_INVALID_MEDIA_POOL,
L"ERROR_DRIVE_MEDIA_MISMATCH",	ERROR_DRIVE_MEDIA_MISMATCH,
L"ERROR_MEDIA_OFFLINE",	ERROR_MEDIA_OFFLINE,
L"ERROR_LIBRARY_OFFLINE",	ERROR_LIBRARY_OFFLINE,
L"ERROR_EMPTY",	ERROR_EMPTY,
L"ERROR_NOT_EMPTY",	ERROR_NOT_EMPTY,
L"ERROR_MEDIA_UNAVAILABLE",	ERROR_MEDIA_UNAVAILABLE,
L"ERROR_RESOURCE_DISABLED",	ERROR_RESOURCE_DISABLED,
L"ERROR_INVALID_CLEANER",	ERROR_INVALID_CLEANER,
L"ERROR_UNABLE_TO_CLEAN",	ERROR_UNABLE_TO_CLEAN,
L"ERROR_OBJECT_NOT_FOUND",	ERROR_OBJECT_NOT_FOUND,
L"ERROR_DATABASE_FAILURE",	ERROR_DATABASE_FAILURE,
L"ERROR_DATABASE_FULL",	ERROR_DATABASE_FULL,
L"ERROR_MEDIA_INCOMPATIBLE",	ERROR_MEDIA_INCOMPATIBLE,
L"ERROR_RESOURCE_NOT_PRESENT",	ERROR_RESOURCE_NOT_PRESENT,
L"ERROR_INVALID_OPERATION",	ERROR_INVALID_OPERATION,
L"ERROR_MEDIA_NOT_AVAILABLE",	ERROR_MEDIA_NOT_AVAILABLE,
L"ERROR_DEVICE_NOT_AVAILABLE",	ERROR_DEVICE_NOT_AVAILABLE,
L"ERROR_REQUEST_REFUSED",	ERROR_REQUEST_REFUSED,
L"ERROR_FILE_OFFLINE",	ERROR_FILE_OFFLINE,
L"ERROR_REMOTE_STORAGE_NOT_ACTIVE",	ERROR_REMOTE_STORAGE_NOT_ACTIVE,
L"ERROR_REMOTE_STORAGE_MEDIA_ERROR",	ERROR_REMOTE_STORAGE_MEDIA_ERROR,
L"ERROR_NOT_A_REPARSE_POINT",	ERROR_NOT_A_REPARSE_POINT,
L"ERROR_REPARSE_ATTRIBUTE_CONFLICT",	ERROR_REPARSE_ATTRIBUTE_CONFLICT,
L"ERROR_DEPENDENT_RESOURCE_EXISTS",	ERROR_DEPENDENT_RESOURCE_EXISTS,
L"ERROR_DEPENDENCY_NOT_FOUND",	ERROR_DEPENDENCY_NOT_FOUND,
L"ERROR_DEPENDENCY_ALREADY_EXISTS",	ERROR_DEPENDENCY_ALREADY_EXISTS,
L"ERROR_RESOURCE_NOT_ONLINE",	ERROR_RESOURCE_NOT_ONLINE,
L"ERROR_HOST_NODE_NOT_AVAILABLE",	ERROR_HOST_NODE_NOT_AVAILABLE,
L"ERROR_RESOURCE_NOT_AVAILABLE",	ERROR_RESOURCE_NOT_AVAILABLE,
L"ERROR_RESOURCE_NOT_FOUND",	ERROR_RESOURCE_NOT_FOUND,
L"ERROR_SHUTDOWN_CLUSTER",	ERROR_SHUTDOWN_CLUSTER,
L"ERROR_CANT_EVICT_ACTIVE_NODE",	ERROR_CANT_EVICT_ACTIVE_NODE,
L"ERROR_OBJECT_ALREADY_EXISTS",	ERROR_OBJECT_ALREADY_EXISTS,
L"ERROR_OBJECT_IN_LIST",	ERROR_OBJECT_IN_LIST,
L"ERROR_GROUP_NOT_AVAILABLE",	ERROR_GROUP_NOT_AVAILABLE,
L"ERROR_GROUP_NOT_FOUND",	ERROR_GROUP_NOT_FOUND,
L"ERROR_GROUP_NOT_ONLINE",	ERROR_GROUP_NOT_ONLINE,
L"ERROR_HOST_NODE_NOT_RESOURCE_OWNER",	ERROR_HOST_NODE_NOT_RESOURCE_OWNER,
L"ERROR_HOST_NODE_NOT_GROUP_OWNER",	ERROR_HOST_NODE_NOT_GROUP_OWNER,
L"ERROR_RESMON_CREATE_FAILED",	ERROR_RESMON_CREATE_FAILED,
L"ERROR_RESMON_ONLINE_FAILED",	ERROR_RESMON_ONLINE_FAILED,
L"ERROR_RESOURCE_ONLINE",	ERROR_RESOURCE_ONLINE,
L"ERROR_QUORUM_RESOURCE",	ERROR_QUORUM_RESOURCE,
L"ERROR_NOT_QUORUM_CAPABLE",	ERROR_NOT_QUORUM_CAPABLE,
L"ERROR_CLUSTER_SHUTTING_DOWN",	ERROR_CLUSTER_SHUTTING_DOWN,
L"ERROR_INVALID_STATE",	ERROR_INVALID_STATE,
L"ERROR_RESOURCE_PROPERTIES_STORED",	ERROR_RESOURCE_PROPERTIES_STORED,
L"ERROR_NOT_QUORUM_CLASS",	ERROR_NOT_QUORUM_CLASS,
L"ERROR_CORE_RESOURCE",	ERROR_CORE_RESOURCE,
L"ERROR_QUORUM_RESOURCE_ONLINE_FAILED",	ERROR_QUORUM_RESOURCE_ONLINE_FAILED,
L"ERROR_QUORUMLOG_OPEN_FAILED",	ERROR_QUORUMLOG_OPEN_FAILED,
L"ERROR_CLUSTERLOG_CORRUPT",	ERROR_CLUSTERLOG_CORRUPT,
L"ERROR_CLUSTERLOG_RECORD_EXCEEDS_MAXSIZE",	ERROR_CLUSTERLOG_RECORD_EXCEEDS_MAXSIZE,
L"ERROR_CLUSTERLOG_EXCEEDS_MAXSIZE",	ERROR_CLUSTERLOG_EXCEEDS_MAXSIZE,
L"ERROR_CLUSTERLOG_CHKPOINT_NOT_FOUND",	ERROR_CLUSTERLOG_CHKPOINT_NOT_FOUND,
L"ERROR_CLUSTERLOG_NOT_ENOUGH_SPACE",	ERROR_CLUSTERLOG_NOT_ENOUGH_SPACE,
L"ERROR_ENCRYPTION_FAILED",	ERROR_ENCRYPTION_FAILED,
L"ERROR_DECRYPTION_FAILED",	ERROR_DECRYPTION_FAILED,
L"ERROR_FILE_ENCRYPTED",	ERROR_FILE_ENCRYPTED,
L"ERROR_NO_RECOVERY_POLICY",	ERROR_NO_RECOVERY_POLICY,
L"ERROR_NO_EFS",	ERROR_NO_EFS,
L"ERROR_WRONG_EFS",	ERROR_WRONG_EFS,
L"ERROR_NO_USER_KEYS",	ERROR_NO_USER_KEYS,
L"ERROR_FILE_NOT_ENCRYPTED",	ERROR_FILE_NOT_ENCRYPTED,
L"ERROR_NOT_EXPORT_FORMAT",	ERROR_NOT_EXPORT_FORMAT,
L"ERROR_NOT_EXPORT_FORMAT",	ERROR_NOT_EXPORT_FORMAT,
NULL,	0,
};

/*
#define ERROR_SUCCESS                    0L
#define ERROR_INVALID_FUNCTION           1L    // dderror
#define ERROR_FILE_NOT_FOUND             2L
#define ERROR_PATH_NOT_FOUND             3L
#define ERROR_TOO_MANY_OPEN_FILES        4L
#define ERROR_ACCESS_DENIED              5L
#define ERROR_INVALID_HANDLE             6L
#define ERROR_ARENA_TRASHED              7L
#define ERROR_NOT_ENOUGH_MEMORY          8L    // dderror
#define ERROR_INVALID_BLOCK              9L
#define ERROR_BAD_ENVIRONMENT            10L
#define ERROR_BAD_FORMAT                 11L
#define ERROR_INVALID_ACCESS             12L
#define ERROR_INVALID_DATA               13L
#define ERROR_OUTOFMEMORY                14L
#define ERROR_INVALID_DRIVE              15L
#define ERROR_CURRENT_DIRECTORY          16L
#define ERROR_NOT_SAME_DEVICE            17L
#define ERROR_NO_MORE_FILES              18L
#define ERROR_WRITE_PROTECT              19L
#define ERROR_BAD_UNIT                   20L
#define ERROR_NOT_READY                  21L
#define ERROR_BAD_COMMAND                22L
#define ERROR_CRC                        23L
#define ERROR_BAD_LENGTH                 24L
#define ERROR_SEEK                       25L
#define ERROR_NOT_DOS_DISK               26L
#define ERROR_SECTOR_NOT_FOUND           27L
#define ERROR_OUT_OF_PAPER               28L
#define ERROR_WRITE_FAULT                29L
#define ERROR_READ_FAULT                 30L
#define ERROR_GEN_FAILURE                31L
#define ERROR_SHARING_VIOLATION          32L
#define ERROR_LOCK_VIOLATION             33L
#define ERROR_WRONG_DISK                 34L
#define ERROR_SHARING_BUFFER_EXCEEDED    36L
#define ERROR_HANDLE_EOF                 38L
#define ERROR_HANDLE_DISK_FULL           39L
#define ERROR_NOT_SUPPORTED              50L
#define ERROR_REM_NOT_LIST               51L
#define ERROR_DUP_NAME                   52L
#define ERROR_BAD_NETPATH                53L
#define ERROR_NETWORK_BUSY               54L
#define ERROR_DEV_NOT_EXIST              55L    // dderror
#define ERROR_TOO_MANY_CMDS              56L
#define ERROR_ADAP_HDW_ERR               57L
#define ERROR_BAD_NET_RESP               58L
#define ERROR_UNEXP_NET_ERR              59L
#define ERROR_BAD_REM_ADAP               60L
#define ERROR_PRINTQ_FULL                61L
#define ERROR_NO_SPOOL_SPACE             62L
#define ERROR_PRINT_CANCELLED            63L
#define ERROR_NETNAME_DELETED            64L
#define ERROR_NETWORK_ACCESS_DENIED      65L
#define ERROR_BAD_DEV_TYPE               66L
#define ERROR_BAD_NET_NAME               67L
#define ERROR_TOO_MANY_NAMES             68L
#define ERROR_TOO_MANY_SESS              69L
#define ERROR_SHARING_PAUSED             70L
#define ERROR_REQ_NOT_ACCEP              71L
#define ERROR_REDIR_PAUSED               72L
#define ERROR_FILE_EXISTS                80L
#define ERROR_CANNOT_MAKE                82L
#define ERROR_FAIL_I24                   83L
#define ERROR_OUT_OF_STRUCTURES          84L
#define ERROR_ALREADY_ASSIGNED           85L
#define ERROR_INVALID_PASSWORD           86L
#define ERROR_INVALID_PARAMETER          87L    // dderror
#define ERROR_NET_WRITE_FAULT            88L
#define ERROR_NO_PROC_SLOTS              89L
#define ERROR_TOO_MANY_SEMAPHORES        100L
#define ERROR_EXCL_SEM_ALREADY_OWNED     101L
#define ERROR_SEM_IS_SET                 102L
#define ERROR_TOO_MANY_SEM_REQUESTS      103L
#define ERROR_INVALID_AT_INTERRUPT_TIME  104L
#define ERROR_SEM_OWNER_DIED             105L
#define ERROR_SEM_USER_LIMIT             106L
#define ERROR_DISK_CHANGE                107L
#define ERROR_DRIVE_LOCKED               108L
#define ERROR_BROKEN_PIPE                109L
#define ERROR_OPEN_FAILED                110L
#define ERROR_BUFFER_OVERFLOW            111L
#define ERROR_DISK_FULL                  112L
#define ERROR_NO_MORE_SEARCH_HANDLES     113L
#define ERROR_INVALID_TARGET_HANDLE      114L
#define ERROR_INVALID_CATEGORY           117L
#define ERROR_INVALID_VERIFY_SWITCH      118L
#define ERROR_BAD_DRIVER_LEVEL           119L
#define ERROR_CALL_NOT_IMPLEMENTED       120L
#define ERROR_SEM_TIMEOUT                121L
#define ERROR_INSUFFICIENT_BUFFER        122L    // dderror
#define ERROR_INVALID_NAME               123L
#define ERROR_INVALID_LEVEL              124L
#define ERROR_NO_VOLUME_LABEL            125L
#define ERROR_MOD_NOT_FOUND              126L
#define ERROR_PROC_NOT_FOUND             127L
#define ERROR_WAIT_NO_CHILDREN           128L
#define ERROR_CHILD_NOT_COMPLETE         129L
#define ERROR_DIRECT_ACCESS_HANDLE       130L
#define ERROR_NEGATIVE_SEEK              131L
#define ERROR_SEEK_ON_DEVICE             132L
#define ERROR_IS_JOIN_TARGET             133L
#define ERROR_IS_JOINED                  134L
#define ERROR_IS_SUBSTED                 135L
#define ERROR_NOT_JOINED                 136L
#define ERROR_NOT_SUBSTED                137L
#define ERROR_JOIN_TO_JOIN               138L
#define ERROR_SUBST_TO_SUBST             139L
#define ERROR_JOIN_TO_SUBST              140L
#define ERROR_SUBST_TO_JOIN              141L
#define ERROR_BUSY_DRIVE                 142L
#define ERROR_SAME_DRIVE                 143L
#define ERROR_DIR_NOT_ROOT               144L
#define ERROR_DIR_NOT_EMPTY              145L
#define ERROR_IS_SUBST_PATH              146L
#define ERROR_IS_JOIN_PATH               147L
#define ERROR_PATH_BUSY                  148L
#define ERROR_IS_SUBST_TARGET            149L
#define ERROR_SYSTEM_TRACE               150L
#define ERROR_INVALID_EVENT_COUNT        151L
#define ERROR_TOO_MANY_MUXWAITERS        152L
#define ERROR_INVALID_LIST_FORMAT        153L
#define ERROR_LABEL_TOO_LONG             154L
#define ERROR_TOO_MANY_TCBS              155L
#define ERROR_SIGNAL_REFUSED             156L
#define ERROR_DISCARDED                  157L
#define ERROR_NOT_LOCKED                 158L
#define ERROR_BAD_THREADID_ADDR          159L
#define ERROR_BAD_ARGUMENTS              160L
#define ERROR_BAD_PATHNAME               161L
#define ERROR_SIGNAL_PENDING             162L
#define ERROR_MAX_THRDS_REACHED          164L
#define ERROR_LOCK_FAILED                167L
#define ERROR_BUSY                       170L
#define ERROR_CANCEL_VIOLATION           173L
#define ERROR_ATOMIC_LOCKS_NOT_SUPPORTED 174L
#define ERROR_INVALID_SEGMENT_NUMBER     180L
#define ERROR_INVALID_ORDINAL            182L
#define ERROR_ALREADY_EXISTS             183L
#define ERROR_INVALID_FLAG_NUMBER        186L
#define ERROR_SEM_NOT_FOUND              187L
#define ERROR_INVALID_STARTING_CODESEG   188L
#define ERROR_INVALID_STACKSEG           189L
#define ERROR_INVALID_MODULETYPE         190L
#define ERROR_INVALID_EXE_SIGNATURE      191L
#define ERROR_EXE_MARKED_INVALID         192L
#define ERROR_BAD_EXE_FORMAT             193L
#define ERROR_ITERATED_DATA_EXCEEDS_64k  194L
#define ERROR_INVALID_MINALLOCSIZE       195L
#define ERROR_DYNLINK_FROM_INVALID_RING  196L
#define ERROR_IOPL_NOT_ENABLED           197L
#define ERROR_INVALID_SEGDPL             198L
#define ERROR_AUTODATASEG_EXCEEDS_64k    199L
#define ERROR_RING2SEG_MUST_BE_MOVABLE   200L
#define ERROR_RELOC_CHAIN_XEEDS_SEGLIM   201L
#define ERROR_INFLOOP_IN_RELOC_CHAIN     202L
#define ERROR_ENVVAR_NOT_FOUND           203L
#define ERROR_NO_SIGNAL_SENT             205L
#define ERROR_FILENAME_EXCED_RANGE       206L
#define ERROR_RING2_STACK_IN_USE         207L
#define ERROR_META_EXPANSION_TOO_LONG    208L
#define ERROR_INVALID_SIGNAL_NUMBER      209L
#define ERROR_THREAD_1_INACTIVE          210L
#define ERROR_LOCKED                     212L
#define ERROR_TOO_MANY_MODULES           214L
#define ERROR_NESTING_NOT_ALLOWED        215L
#define ERROR_EXE_MACHINE_TYPE_MISMATCH  216L
#define ERROR_BAD_PIPE                   230L
#define ERROR_PIPE_BUSY                  231L
#define ERROR_NO_DATA                    232L
#define ERROR_PIPE_NOT_CONNECTED         233L
#define ERROR_MORE_DATA                  234L    // dderror
#define ERROR_VC_DISCONNECTED            240L
#define ERROR_INVALID_EA_NAME            254L
#define ERROR_EA_LIST_INCONSISTENT       255L
#define ERROR_NO_MORE_ITEMS              259L
#define ERROR_CANNOT_COPY                266L
#define ERROR_DIRECTORY                  267L
#define ERROR_EAS_DIDNT_FIT              275L
#define ERROR_EA_FILE_CORRUPT            276L
#define ERROR_EA_TABLE_FULL              277L
#define ERROR_INVALID_EA_HANDLE          278L
#define ERROR_EAS_NOT_SUPPORTED          282L
#define ERROR_NOT_OWNER                  288L
#define ERROR_TOO_MANY_POSTS             298L
#define ERROR_PARTIAL_COPY               299L
#define ERROR_OPLOCK_NOT_GRANTED         300L
#define ERROR_INVALID_OPLOCK_PROTOCOL    301L
#define ERROR_MR_MID_NOT_FOUND           317L
#define ERROR_INVALID_ADDRESS            487L
#define ERROR_ARITHMETIC_OVERFLOW        534L
#define ERROR_PIPE_CONNECTED             535L
#define ERROR_PIPE_LISTENING             536L
#define ERROR_EA_ACCESS_DENIED           994L
#define ERROR_OPERATION_ABORTED          995L
#define ERROR_IO_INCOMPLETE              996L
#define ERROR_IO_PENDING                 997L    // dderror
#define ERROR_NOACCESS                   998L
#define ERROR_SWAPERROR                  999L
#define ERROR_STACK_OVERFLOW             1001L
#define ERROR_INVALID_MESSAGE            1002L
#define ERROR_CAN_NOT_COMPLETE           1003L
#define ERROR_INVALID_FLAGS              1004L
#define ERROR_UNRECOGNIZED_VOLUME        1005L
#define ERROR_FILE_INVALID               1006L
#define ERROR_FULLSCREEN_MODE            1007L
#define ERROR_NO_TOKEN                   1008L
#define ERROR_BADDB                      1009L
#define ERROR_BADKEY                     1010L
#define ERROR_CANTOPEN                   1011L
#define ERROR_CANTREAD                   1012L
#define ERROR_CANTWRITE                  1013L
#define ERROR_REGISTRY_RECOVERED         1014L
#define ERROR_REGISTRY_CORRUPT           1015L
#define ERROR_REGISTRY_IO_FAILED         1016L
#define ERROR_NOT_REGISTRY_FILE          1017L
#define ERROR_KEY_DELETED                1018L
#define ERROR_NO_LOG_SPACE               1019L
#define ERROR_KEY_HAS_CHILDREN           1020L
#define ERROR_CHILD_MUST_BE_VOLATILE     1021L
#define ERROR_NOTIFY_ENUM_DIR            1022L
#define ERROR_DEPENDENT_SERVICES_RUNNING 1051L
#define ERROR_INVALID_SERVICE_CONTROL    1052L
#define ERROR_SERVICE_REQUEST_TIMEOUT    1053L
#define ERROR_SERVICE_NO_THREAD          1054L
#define ERROR_SERVICE_DATABASE_LOCKED    1055L
#define ERROR_SERVICE_ALREADY_RUNNING    1056L
#define ERROR_INVALID_SERVICE_ACCOUNT    1057L
#define ERROR_SERVICE_DISABLED           1058L
#define ERROR_CIRCULAR_DEPENDENCY        1059L
#define ERROR_SERVICE_DOES_NOT_EXIST     1060L
#define ERROR_SERVICE_CANNOT_ACCEPT_CTRL 1061L
#define ERROR_SERVICE_NOT_ACTIVE         1062L
#define ERROR_FAILED_SERVICE_CONTROLLER_CONNECT 1063L
#define ERROR_EXCEPTION_IN_SERVICE       1064L
#define ERROR_DATABASE_DOES_NOT_EXIST    1065L
#define ERROR_SERVICE_SPECIFIC_ERROR     1066L
#define ERROR_PROCESS_ABORTED            1067L
#define ERROR_SERVICE_DEPENDENCY_FAIL    1068L
#define ERROR_SERVICE_LOGON_FAILED       1069L
#define ERROR_SERVICE_START_HANG         1070L
#define ERROR_INVALID_SERVICE_LOCK       1071L
#define ERROR_SERVICE_MARKED_FOR_DELETE  1072L
#define ERROR_SERVICE_EXISTS             1073L
#define ERROR_ALREADY_RUNNING_LKG        1074L
#define ERROR_SERVICE_DEPENDENCY_DELETED 1075L
#define ERROR_BOOT_ALREADY_ACCEPTED      1076L
#define ERROR_SERVICE_NEVER_STARTED      1077L
#define ERROR_DUPLICATE_SERVICE_NAME     1078L
#define ERROR_DIFFERENT_SERVICE_ACCOUNT  1079L
#define ERROR_CANNOT_DETECT_DRIVER_FAILURE 1080L
#define ERROR_CANNOT_DETECT_PROCESS_ABORT 1081L
#define ERROR_NO_RECOVERY_PROGRAM        1082L
#define ERROR_END_OF_MEDIA               1100L
#define ERROR_FILEMARK_DETECTED          1101L
#define ERROR_BEGINNING_OF_MEDIA         1102L
#define ERROR_SETMARK_DETECTED           1103L
#define ERROR_NO_DATA_DETECTED           1104L
#define ERROR_PARTITION_FAILURE          1105L
#define ERROR_INVALID_BLOCK_LENGTH       1106L
#define ERROR_DEVICE_NOT_PARTITIONED     1107L
#define ERROR_UNABLE_TO_LOCK_MEDIA       1108L
#define ERROR_UNABLE_TO_UNLOAD_MEDIA     1109L
#define ERROR_MEDIA_CHANGED              1110L
#define ERROR_BUS_RESET                  1111L
#define ERROR_NO_MEDIA_IN_DRIVE          1112L
#define ERROR_NO_UNICODE_TRANSLATION     1113L
#define ERROR_DLL_INIT_FAILED            1114L
#define ERROR_SHUTDOWN_IN_PROGRESS       1115L
#define ERROR_NO_SHUTDOWN_IN_PROGRESS    1116L
#define ERROR_IO_DEVICE                  1117L
#define ERROR_SERIAL_NO_DEVICE           1118L
#define ERROR_IRQ_BUSY                   1119L
#define ERROR_MORE_WRITES                1120L
#define ERROR_COUNTER_TIMEOUT            1121L
#define ERROR_FLOPPY_ID_MARK_NOT_FOUND   1122L
#define ERROR_FLOPPY_WRONG_CYLINDER      1123L
#define ERROR_FLOPPY_UNKNOWN_ERROR       1124L
#define ERROR_FLOPPY_BAD_REGISTERS       1125L
#define ERROR_DISK_RECALIBRATE_FAILED    1126L
#define ERROR_DISK_OPERATION_FAILED      1127L
#define ERROR_DISK_RESET_FAILED          1128L
#define ERROR_EOM_OVERFLOW               1129L
#define ERROR_NOT_ENOUGH_SERVER_MEMORY   1130L
#define ERROR_POSSIBLE_DEADLOCK          1131L
#define ERROR_MAPPED_ALIGNMENT           1132L
#define ERROR_SET_POWER_STATE_VETOED     1140L
#define ERROR_SET_POWER_STATE_FAILED     1141L
#define ERROR_TOO_MANY_LINKS             1142L
#define ERROR_OLD_WIN_VERSION            1150L
#define ERROR_APP_WRONG_OS               1151L
#define ERROR_SINGLE_INSTANCE_APP        1152L
#define ERROR_RMODE_APP                  1153L
#define ERROR_INVALID_DLL                1154L
#define ERROR_NO_ASSOCIATION             1155L
#define ERROR_DDE_FAIL                   1156L
#define ERROR_DLL_NOT_FOUND              1157L
#define ERROR_NO_MORE_USER_HANDLES       1158L
#define ERROR_MESSAGE_SYNC_ONLY          1159L
#define ERROR_SOURCE_ELEMENT_EMPTY       1160L
#define ERROR_DESTINATION_ELEMENT_FULL   1161L
#define ERROR_ILLEGAL_ELEMENT_ADDRESS    1162L
#define ERROR_MAGAZINE_NOT_PRESENT       1163L
#define ERROR_DEVICE_REINITIALIZATION_NEEDED 1164L    // dderror
#define ERROR_DEVICE_REQUIRES_CLEANING   1165L
#define ERROR_DEVICE_DOOR_OPEN           1166L
#define ERROR_DEVICE_NOT_CONNECTED       1167L
#define ERROR_NOT_FOUND                  1168L
#define ERROR_NO_MATCH                   1169L
#define ERROR_SET_NOT_FOUND              1170L
#define ERROR_POINT_NOT_FOUND            1171L
#define ERROR_NO_TRACKING_SERVICE        1172L
#define ERROR_NO_VOLUME_ID               1173L
#define ERROR_CONNECTED_OTHER_PASSWORD   2108L
#define ERROR_BAD_USERNAME               2202L
#define ERROR_NOT_CONNECTED              2250L
#define ERROR_OPEN_FILES                 2401L
#define ERROR_ACTIVE_CONNECTIONS         2402L
#define ERROR_DEVICE_IN_USE              2404L
#define ERROR_BAD_DEVICE                 1200L
#define ERROR_CONNECTION_UNAVAIL         1201L
#define ERROR_DEVICE_ALREADY_REMEMBERED  1202L
#define ERROR_NO_NET_OR_BAD_PATH         1203L
#define ERROR_BAD_PROVIDER               1204L
#define ERROR_CANNOT_OPEN_PROFILE        1205L
#define ERROR_BAD_PROFILE                1206L
#define ERROR_NOT_CONTAINER              1207L
#define ERROR_EXTENDED_ERROR             1208L
#define ERROR_INVALID_GROUPNAME          1209L
#define ERROR_INVALID_COMPUTERNAME       1210L
#define ERROR_INVALID_EVENTNAME          1211L
#define ERROR_INVALID_DOMAINNAME         1212L
#define ERROR_INVALID_SERVICENAME        1213L
#define ERROR_INVALID_NETNAME            1214L
#define ERROR_INVALID_SHARENAME          1215L
#define ERROR_INVALID_PASSWORDNAME       1216L
#define ERROR_INVALID_MESSAGENAME        1217L
#define ERROR_INVALID_MESSAGEDEST        1218L
#define ERROR_SESSION_CREDENTIAL_CONFLICT 1219L
#define ERROR_REMOTE_SESSION_LIMIT_EXCEEDED 1220L
#define ERROR_DUP_DOMAINNAME             1221L
#define ERROR_NO_NETWORK                 1222L
#define ERROR_CANCELLED                  1223L
#define ERROR_USER_MAPPED_FILE           1224L
#define ERROR_CONNECTION_REFUSED         1225L
#define ERROR_GRACEFUL_DISCONNECT        1226L
#define ERROR_ADDRESS_ALREADY_ASSOCIATED 1227L
#define ERROR_ADDRESS_NOT_ASSOCIATED     1228L
#define ERROR_CONNECTION_INVALID         1229L
#define ERROR_CONNECTION_ACTIVE          1230L
#define ERROR_NETWORK_UNREACHABLE        1231L
#define ERROR_HOST_UNREACHABLE           1232L
#define ERROR_PROTOCOL_UNREACHABLE       1233L
#define ERROR_PORT_UNREACHABLE           1234L
#define ERROR_REQUEST_ABORTED            1235L
#define ERROR_CONNECTION_ABORTED         1236L
#define ERROR_RETRY                      1237L
#define ERROR_CONNECTION_COUNT_LIMIT     1238L
#define ERROR_LOGIN_TIME_RESTRICTION     1239L
#define ERROR_LOGIN_WKSTA_RESTRICTION    1240L
#define ERROR_INCORRECT_ADDRESS          1241L
#define ERROR_ALREADY_REGISTERED         1242L
#define ERROR_SERVICE_NOT_FOUND          1243L
#define ERROR_NOT_AUTHENTICATED          1244L
#define ERROR_NOT_LOGGED_ON              1245L
#define ERROR_CONTINUE                   1246L
#define ERROR_ALREADY_INITIALIZED        1247L
#define ERROR_NO_MORE_DEVICES            1248L
#define ERROR_NO_SUCH_SITE               1249L
#define ERROR_DOMAIN_CONTROLLER_EXISTS   1250L
#define ERROR_DS_NOT_INSTALLED           1251L
#define ERROR_NOT_ALL_ASSIGNED           1300L
#define ERROR_SOME_NOT_MAPPED            1301L
#define ERROR_NO_QUOTAS_FOR_ACCOUNT      1302L
#define ERROR_LOCAL_USER_SESSION_KEY     1303L
#define ERROR_NULL_LM_PASSWORD           1304L
#define ERROR_UNKNOWN_REVISION           1305L
#define ERROR_REVISION_MISMATCH          1306L
#define ERROR_INVALID_OWNER              1307L
#define ERROR_INVALID_PRIMARY_GROUP      1308L
#define ERROR_NO_IMPERSONATION_TOKEN     1309L
#define ERROR_CANT_DISABLE_MANDATORY     1310L
#define ERROR_NO_LOGON_SERVERS           1311L
#define ERROR_NO_SUCH_LOGON_SESSION      1312L
#define ERROR_NO_SUCH_PRIVILEGE          1313L
#define ERROR_PRIVILEGE_NOT_HELD         1314L
#define ERROR_INVALID_ACCOUNT_NAME       1315L
#define ERROR_USER_EXISTS                1316L
#define ERROR_NO_SUCH_USER               1317L
#define ERROR_GROUP_EXISTS               1318L
#define ERROR_NO_SUCH_GROUP              1319L
#define ERROR_MEMBER_IN_GROUP            1320L
#define ERROR_MEMBER_NOT_IN_GROUP        1321L
#define ERROR_LAST_ADMIN                 1322L
#define ERROR_WRONG_PASSWORD             1323L
#define ERROR_ILL_FORMED_PASSWORD        1324L
#define ERROR_PASSWORD_RESTRICTION       1325L
#define ERROR_LOGON_FAILURE              1326L
#define ERROR_ACCOUNT_RESTRICTION        1327L
#define ERROR_INVALID_LOGON_HOURS        1328L
#define ERROR_INVALID_WORKSTATION        1329L
#define ERROR_PASSWORD_EXPIRED           1330L
#define ERROR_ACCOUNT_DISABLED           1331L
#define ERROR_NONE_MAPPED                1332L
#define ERROR_TOO_MANY_LUIDS_REQUESTED   1333L
#define ERROR_LUIDS_EXHAUSTED            1334L
#define ERROR_INVALID_SUB_AUTHORITY      1335L
#define ERROR_INVALID_ACL                1336L
#define ERROR_INVALID_SID                1337L
#define ERROR_INVALID_SECURITY_DESCR     1338L
#define ERROR_BAD_INHERITANCE_ACL        1340L
#define ERROR_SERVER_DISABLED            1341L
#define ERROR_SERVER_NOT_DISABLED        1342L
#define ERROR_INVALID_ID_AUTHORITY       1343L
#define ERROR_ALLOTTED_SPACE_EXCEEDED    1344L
#define ERROR_INVALID_GROUP_ATTRIBUTES   1345L
#define ERROR_BAD_IMPERSONATION_LEVEL    1346L
#define ERROR_CANT_OPEN_ANONYMOUS        1347L
#define ERROR_BAD_VALIDATION_CLASS       1348L
#define ERROR_BAD_TOKEN_TYPE             1349L
#define ERROR_NO_SECURITY_ON_OBJECT      1350L
#define ERROR_CANT_ACCESS_DOMAIN_INFO    1351L
#define ERROR_INVALID_SERVER_STATE       1352L
#define ERROR_INVALID_DOMAIN_STATE       1353L
#define ERROR_INVALID_DOMAIN_ROLE        1354L
#define ERROR_NO_SUCH_DOMAIN             1355L
#define ERROR_DOMAIN_EXISTS              1356L
#define ERROR_DOMAIN_LIMIT_EXCEEDED      1357L
#define ERROR_INTERNAL_DB_CORRUPTION     1358L
#define ERROR_INTERNAL_ERROR             1359L
#define ERROR_GENERIC_NOT_MAPPED         1360L
#define ERROR_BAD_DESCRIPTOR_FORMAT      1361L
#define ERROR_NOT_LOGON_PROCESS          1362L
#define ERROR_LOGON_SESSION_EXISTS       1363L
#define ERROR_NO_SUCH_PACKAGE            1364L
#define ERROR_BAD_LOGON_SESSION_STATE    1365L
#define ERROR_LOGON_SESSION_COLLISION    1366L
#define ERROR_INVALID_LOGON_TYPE         1367L
#define ERROR_CANNOT_IMPERSONATE         1368L
#define ERROR_RXACT_INVALID_STATE        1369L
#define ERROR_RXACT_COMMIT_FAILURE       1370L
#define ERROR_SPECIAL_ACCOUNT            1371L
#define ERROR_SPECIAL_GROUP              1372L
#define ERROR_SPECIAL_USER               1373L
#define ERROR_MEMBERS_PRIMARY_GROUP      1374L
#define ERROR_TOKEN_ALREADY_IN_USE       1375L
#define ERROR_NO_SUCH_ALIAS              1376L
#define ERROR_MEMBER_NOT_IN_ALIAS        1377L
#define ERROR_MEMBER_IN_ALIAS            1378L
#define ERROR_ALIAS_EXISTS               1379L
#define ERROR_LOGON_NOT_GRANTED          1380L
#define ERROR_TOO_MANY_SECRETS           1381L
#define ERROR_SECRET_TOO_LONG            1382L
#define ERROR_INTERNAL_DB_ERROR          1383L
#define ERROR_TOO_MANY_CONTEXT_IDS       1384L
#define ERROR_LOGON_TYPE_NOT_GRANTED     1385L
#define ERROR_NT_CROSS_ENCRYPTION_REQUIRED 1386L
#define ERROR_NO_SUCH_MEMBER             1387L
#define ERROR_INVALID_MEMBER             1388L
#define ERROR_TOO_MANY_SIDS              1389L
#define ERROR_LM_CROSS_ENCRYPTION_REQUIRED 1390L
#define ERROR_NO_INHERITANCE             1391L
#define ERROR_FILE_CORRUPT               1392L
#define ERROR_DISK_CORRUPT               1393L
#define ERROR_NO_USER_SESSION_KEY        1394L
#define ERROR_LICENSE_QUOTA_EXCEEDED     1395L
#define ERROR_INVALID_WINDOW_HANDLE      1400L
#define ERROR_INVALID_MENU_HANDLE        1401L
#define ERROR_INVALID_CURSOR_HANDLE      1402L
#define ERROR_INVALID_ACCEL_HANDLE       1403L
#define ERROR_INVALID_HOOK_HANDLE        1404L
#define ERROR_INVALID_DWP_HANDLE         1405L
#define ERROR_TLW_WITH_WSCHILD           1406L
#define ERROR_CANNOT_FIND_WND_CLASS      1407L
#define ERROR_WINDOW_OF_OTHER_THREAD     1408L
#define ERROR_HOTKEY_ALREADY_REGISTERED  1409L
#define ERROR_CLASS_ALREADY_EXISTS       1410L
#define ERROR_CLASS_DOES_NOT_EXIST       1411L
#define ERROR_CLASS_HAS_WINDOWS          1412L
#define ERROR_INVALID_INDEX              1413L
#define ERROR_INVALID_ICON_HANDLE        1414L
#define ERROR_PRIVATE_DIALOG_INDEX       1415L
#define ERROR_LISTBOX_ID_NOT_FOUND       1416L
#define ERROR_NO_WILDCARD_CHARACTERS     1417L
#define ERROR_CLIPBOARD_NOT_OPEN         1418L
#define ERROR_HOTKEY_NOT_REGISTERED      1419L
#define ERROR_WINDOW_NOT_DIALOG          1420L
#define ERROR_CONTROL_ID_NOT_FOUND       1421L
#define ERROR_INVALID_COMBOBOX_MESSAGE   1422L
#define ERROR_WINDOW_NOT_COMBOBOX        1423L
#define ERROR_INVALID_EDIT_HEIGHT        1424L
#define ERROR_DC_NOT_FOUND               1425L
#define ERROR_INVALID_HOOK_FILTER        1426L
#define ERROR_INVALID_FILTER_PROC        1427L
#define ERROR_HOOK_NEEDS_HMOD            1428L
#define ERROR_GLOBAL_ONLY_HOOK           1429L
#define ERROR_JOURNAL_HOOK_SET           1430L
#define ERROR_HOOK_NOT_INSTALLED         1431L
#define ERROR_INVALID_LB_MESSAGE         1432L
#define ERROR_SETCOUNT_ON_BAD_LB         1433L
#define ERROR_LB_WITHOUT_TABSTOPS        1434L
#define ERROR_DESTROY_OBJECT_OF_OTHER_THREAD 1435L
#define ERROR_CHILD_WINDOW_MENU          1436L
#define ERROR_NO_SYSTEM_MENU             1437L
#define ERROR_INVALID_MSGBOX_STYLE       1438L
#define ERROR_INVALID_SPI_VALUE          1439L
#define ERROR_SCREEN_ALREADY_LOCKED      1440L
#define ERROR_HWNDS_HAVE_DIFF_PARENT     1441L
#define ERROR_NOT_CHILD_WINDOW           1442L
#define ERROR_INVALID_GW_COMMAND         1443L
#define ERROR_INVALID_THREAD_ID          1444L
#define ERROR_NON_MDICHILD_WINDOW        1445L
#define ERROR_POPUP_ALREADY_ACTIVE       1446L
#define ERROR_NO_SCROLLBARS              1447L
#define ERROR_INVALID_SCROLLBAR_RANGE    1448L
#define ERROR_INVALID_SHOWWIN_COMMAND    1449L
#define ERROR_NO_SYSTEM_RESOURCES        1450L
#define ERROR_NONPAGED_SYSTEM_RESOURCES  1451L
#define ERROR_PAGED_SYSTEM_RESOURCES     1452L
#define ERROR_WORKING_SET_QUOTA          1453L
#define ERROR_PAGEFILE_QUOTA             1454L
#define ERROR_COMMITMENT_LIMIT           1455L
#define ERROR_MENU_ITEM_NOT_FOUND        1456L
#define ERROR_INVALID_KEYBOARD_HANDLE    1457L
#define ERROR_HOOK_TYPE_NOT_ALLOWED      1458L
#define ERROR_REQUIRES_INTERACTIVE_WINDOWSTATION 1459L
#define ERROR_TIMEOUT                    1460L
#define ERROR_INVALID_MONITOR_HANDLE     1461L
#define ERROR_EVENTLOG_FILE_CORRUPT      1500L
#define ERROR_EVENTLOG_CANT_START        1501L
#define ERROR_LOG_FILE_FULL              1502L
#define ERROR_EVENTLOG_FILE_CHANGED      1503L
#define ERROR_INSTALL_SERVICE            1601L
#define ERROR_INSTALL_USEREXIT           1602L
#define ERROR_INSTALL_FAILURE            1603L
#define ERROR_INSTALL_SUSPEND            1604L
#define ERROR_UNKNOWN_PRODUCT            1605L
#define ERROR_UNKNOWN_FEATURE            1606L
#define ERROR_UNKNOWN_COMPONENT          1607L
#define ERROR_UNKNOWN_PROPERTY           1608L
#define ERROR_INVALID_HANDLE_STATE       1609L
#define ERROR_BAD_CONFIGURATION          1610L
#define ERROR_INDEX_ABSENT               1611L
#define ERROR_INSTALL_SOURCE_ABSENT      1612L
#define ERROR_BAD_DATABASE_VERSION       1613L
#define ERROR_PRODUCT_UNINSTALLED        1614L
#define ERROR_BAD_QUERY_SYNTAX           1615L
#define ERROR_INVALID_FIELD              1616L
#define ERROR_INVALID_USER_BUFFER        1784L
#define ERROR_UNRECOGNIZED_MEDIA         1785L
#define ERROR_NO_TRUST_LSA_SECRET        1786L
#define ERROR_NO_TRUST_SAM_ACCOUNT       1787L
#define ERROR_TRUSTED_DOMAIN_FAILURE     1788L
#define ERROR_TRUSTED_RELATIONSHIP_FAILURE 1789L
#define ERROR_TRUST_FAILURE              1790L
#define ERROR_NETLOGON_NOT_STARTED       1792L
#define ERROR_ACCOUNT_EXPIRED            1793L
#define ERROR_REDIRECTOR_HAS_OPEN_HANDLES 1794L
#define ERROR_PRINTER_DRIVER_ALREADY_INSTALLED 1795L
#define ERROR_UNKNOWN_PORT               1796L
#define ERROR_UNKNOWN_PRINTER_DRIVER     1797L
#define ERROR_UNKNOWN_PRINTPROCESSOR     1798L
#define ERROR_INVALID_SEPARATOR_FILE     1799L
#define ERROR_INVALID_PRIORITY           1800L
#define ERROR_INVALID_PRINTER_NAME       1801L
#define ERROR_PRINTER_ALREADY_EXISTS     1802L
#define ERROR_INVALID_PRINTER_COMMAND    1803L
#define ERROR_INVALID_DATATYPE           1804L
#define ERROR_INVALID_ENVIRONMENT        1805L
#define ERROR_NOLOGON_INTERDOMAIN_TRUST_ACCOUNT 1807L
#define ERROR_NOLOGON_WORKSTATION_TRUST_ACCOUNT 1808L
#define ERROR_NOLOGON_SERVER_TRUST_ACCOUNT 1809L
#define ERROR_DOMAIN_TRUST_INCONSISTENT  1810L
#define ERROR_SERVER_HAS_OPEN_HANDLES    1811L
#define ERROR_RESOURCE_DATA_NOT_FOUND    1812L
#define ERROR_RESOURCE_TYPE_NOT_FOUND    1813L
#define ERROR_RESOURCE_NAME_NOT_FOUND    1814L
#define ERROR_RESOURCE_LANG_NOT_FOUND    1815L
#define ERROR_NOT_ENOUGH_QUOTA           1816L
#define ERROR_INVALID_TIME               1901L
#define ERROR_INVALID_FORM_NAME          1902L
#define ERROR_INVALID_FORM_SIZE          1903L
#define ERROR_ALREADY_WAITING            1904L
#define ERROR_PRINTER_DELETED            1905L
#define ERROR_INVALID_PRINTER_STATE      1906L
#define ERROR_PASSWORD_MUST_CHANGE       1907L
#define ERROR_DOMAIN_CONTROLLER_NOT_FOUND 1908L
#define ERROR_ACCOUNT_LOCKED_OUT         1909L
#define ERROR_NO_SITENAME                1919L
#define ERROR_CANT_ACCESS_FILE           1920L
#define ERROR_CANT_RESOLVE_FILENAME      1921L
#define ERROR_DS_MEMBERSHIP_EVALUATED_LOCALLY 1922L
#define ERROR_DS_NO_ATTRIBUTE_OR_VALUE   1923L
#define ERROR_DS_INVALID_ATTRIBUTE_SYNTAX 1924L
#define ERROR_DS_ATTRIBUTE_TYPE_UNDEFINED 1925L
#define ERROR_DS_ATTRIBUTE_OR_VALUE_EXISTS 1926L
#define ERROR_DS_BUSY                    1927L
#define ERROR_DS_UNAVAILABLE             1928L
#define ERROR_DS_NO_RIDS_ALLOCATED       1929L
#define ERROR_DS_NO_MORE_RIDS            1930L
#define ERROR_DS_INCORRECT_ROLE_OWNER    1931L
#define ERROR_DS_RIDMGR_INIT_ERROR       1932L
#define ERROR_DS_OBJ_CLASS_VIOLATION     1933L
#define ERROR_DS_CANT_ON_NON_LEAF        1934L
#define ERROR_DS_CANT_ON_RDN             1935L
#define ERROR_DS_CANT_MOD_OBJ_CLASS      1936L
#define ERROR_DS_CROSS_DOM_MOVE_ERROR    1937L
#define ERROR_DS_GC_NOT_AVAILABLE        1938L
#define ERROR_NO_BROWSER_SERVERS_FOUND   6118L
#define ERROR_INVALID_PIXEL_FORMAT       2000L
#define ERROR_BAD_DRIVER                 2001L
#define ERROR_INVALID_WINDOW_STYLE       2002L
#define ERROR_METAFILE_NOT_SUPPORTED     2003L
#define ERROR_TRANSFORM_NOT_SUPPORTED    2004L
#define ERROR_CLIPPING_NOT_SUPPORTED     2005L
#define ERROR_INVALID_CMM                2300L
#define ERROR_INVALID_PROFILE            2301L
#define ERROR_TAG_NOT_FOUND              2302L
#define ERROR_TAG_NOT_PRESENT            2303L
#define ERROR_DUPLICATE_TAG              2304L
#define ERROR_PROFILE_NOT_ASSOCIATED_WITH_DEVICE 2305L
#define ERROR_PROFILE_NOT_FOUND          2306L
#define ERROR_INVALID_COLORSPACE         2307L
#define ERROR_ICM_NOT_ENABLED            2308L
#define ERROR_DELETING_ICM_XFORM         2309L
#define ERROR_INVALID_TRANSFORM          2310L
#define ERROR_UNKNOWN_PRINT_MONITOR      3000L
#define ERROR_PRINTER_DRIVER_IN_USE      3001L
#define ERROR_SPOOL_FILE_NOT_FOUND       3002L
#define ERROR_SPL_NO_STARTDOC            3003L
#define ERROR_SPL_NO_ADDJOB              3004L
#define ERROR_PRINT_PROCESSOR_ALREADY_INSTALLED 3005L
#define ERROR_PRINT_MONITOR_ALREADY_INSTALLED 3006L
#define ERROR_INVALID_PRINT_MONITOR      3007L
#define ERROR_PRINT_MONITOR_IN_USE       3008L
#define ERROR_PRINTER_HAS_JOBS_QUEUED    3009L
#define ERROR_SUCCESS_REBOOT_REQUIRED    3010L
#define ERROR_SUCCESS_RESTART_REQUIRED   3011L
#define ERROR_WINS_INTERNAL              4000L
#define ERROR_CAN_NOT_DEL_LOCAL_WINS     4001L
#define ERROR_STATIC_INIT                4002L
#define ERROR_INC_BACKUP                 4003L
#define ERROR_FULL_BACKUP                4004L
#define ERROR_REC_NON_EXISTENT           4005L
#define ERROR_RPL_NOT_ALLOWED            4006L
#define ERROR_DHCP_ADDRESS_CONFLICT      4100L
#define ERROR_WMI_GUID_NOT_FOUND         4200L
#define ERROR_WMI_INSTANCE_NOT_FOUND     4201L
#define ERROR_WMI_ITEMID_NOT_FOUND       4202L
#define ERROR_WMI_TRY_AGAIN              4203L
#define ERROR_WMI_DP_NOT_FOUND           4204L
#define ERROR_WMI_UNRESOLVED_INSTANCE_REF 4205L
#define ERROR_WMI_ALREADY_ENABLED        4206L
#define ERROR_WMI_GUID_DISCONNECTED      4207L
#define ERROR_WMI_SERVER_UNAVAILABLE     4208L
#define ERROR_WMI_DP_FAILED              4209L
#define ERROR_WMI_INVALID_MOF            4210L
#define ERROR_WMI_INVALID_REGINFO        4211L
#define ERROR_INVALID_MEDIA              4300L
#define ERROR_INVALID_LIBRARY            4301L
#define ERROR_INVALID_MEDIA_POOL         4302L
#define ERROR_DRIVE_MEDIA_MISMATCH       4303L
#define ERROR_MEDIA_OFFLINE              4304L
#define ERROR_LIBRARY_OFFLINE            4305L
#define ERROR_EMPTY                      4306L
#define ERROR_NOT_EMPTY                  4307L
#define ERROR_MEDIA_UNAVAILABLE          4308L
#define ERROR_RESOURCE_DISABLED          4309L
#define ERROR_INVALID_CLEANER            4310L
#define ERROR_UNABLE_TO_CLEAN            4311L
#define ERROR_OBJECT_NOT_FOUND           4312L
#define ERROR_DATABASE_FAILURE           4313L
#define ERROR_DATABASE_FULL              4314L
#define ERROR_MEDIA_INCOMPATIBLE         4315L
#define ERROR_RESOURCE_NOT_PRESENT       4316L
#define ERROR_INVALID_OPERATION          4317L
#define ERROR_MEDIA_NOT_AVAILABLE        4318L
#define ERROR_DEVICE_NOT_AVAILABLE       4319L
#define ERROR_REQUEST_REFUSED            4320L
#define ERROR_FILE_OFFLINE               4350L
#define ERROR_REMOTE_STORAGE_NOT_ACTIVE  4351L
#define ERROR_REMOTE_STORAGE_MEDIA_ERROR 4352L
#define ERROR_NOT_A_REPARSE_POINT        4390L
#define ERROR_REPARSE_ATTRIBUTE_CONFLICT 4391L
#define ERROR_DEPENDENT_RESOURCE_EXISTS  5001L
#define ERROR_DEPENDENCY_NOT_FOUND       5002L
#define ERROR_DEPENDENCY_ALREADY_EXISTS  5003L
#define ERROR_RESOURCE_NOT_ONLINE        5004L
#define ERROR_HOST_NODE_NOT_AVAILABLE    5005L
#define ERROR_RESOURCE_NOT_AVAILABLE     5006L
#define ERROR_RESOURCE_NOT_FOUND         5007L
#define ERROR_SHUTDOWN_CLUSTER           5008L
#define ERROR_CANT_EVICT_ACTIVE_NODE     5009L
#define ERROR_OBJECT_ALREADY_EXISTS      5010L
#define ERROR_OBJECT_IN_LIST             5011L
#define ERROR_GROUP_NOT_AVAILABLE        5012L
#define ERROR_GROUP_NOT_FOUND            5013L
#define ERROR_GROUP_NOT_ONLINE           5014L
#define ERROR_HOST_NODE_NOT_RESOURCE_OWNER 5015L
#define ERROR_HOST_NODE_NOT_GROUP_OWNER  5016L
#define ERROR_RESMON_CREATE_FAILED       5017L
#define ERROR_RESMON_ONLINE_FAILED       5018L
#define ERROR_RESOURCE_ONLINE            5019L
#define ERROR_QUORUM_RESOURCE            5020L
#define ERROR_NOT_QUORUM_CAPABLE         5021L
#define ERROR_CLUSTER_SHUTTING_DOWN      5022L
#define ERROR_INVALID_STATE              5023L
#define ERROR_RESOURCE_PROPERTIES_STORED 5024L
#define ERROR_NOT_QUORUM_CLASS           5025L
#define ERROR_CORE_RESOURCE              5026L
#define ERROR_QUORUM_RESOURCE_ONLINE_FAILED 5027L
#define ERROR_QUORUMLOG_OPEN_FAILED      5028L
#define ERROR_CLUSTERLOG_CORRUPT         5029L
#define ERROR_CLUSTERLOG_RECORD_EXCEEDS_MAXSIZE 5030L
#define ERROR_CLUSTERLOG_EXCEEDS_MAXSIZE 5031L
#define ERROR_CLUSTERLOG_CHKPOINT_NOT_FOUND 5032L
#define ERROR_CLUSTERLOG_NOT_ENOUGH_SPACE 5033L
#define ERROR_ENCRYPTION_FAILED          6000L
#define ERROR_DECRYPTION_FAILED          6001L
#define ERROR_FILE_ENCRYPTED             6002L
#define ERROR_NO_RECOVERY_POLICY         6003L
#define ERROR_NO_EFS                     6004L
#define ERROR_WRONG_EFS                  6005L
#define ERROR_NO_USER_KEYS               6006L
#define ERROR_FILE_NOT_ENCRYPTED         6007L
#define ERROR_NOT_EXPORT_FORMAT          6008L
*/

/*
#define WM_NULL                         0x0000
#define WM_CREATE                       0x0001
#define WM_DESTROY                      0x0002
#define WM_MOVE                         0x0003
#define WM_SIZE                         0x0005

#define WM_ACTIVATE                     0x0006
//
// WM_ACTIVATE state values
 
#define     WA_INACTIVE     0
#define     WA_ACTIVE       1
#define     WA_CLICKACTIVE  2

#define WM_SETFOCUS                     0x0007
#define WM_KILLFOCUS                    0x0008
#define WM_ENABLE                       0x000A
#define WM_SETREDRAW                    0x000B
#define WM_SETTEXT                      0x000C
#define WM_GETTEXT                      0x000D
#define WM_GETTEXTLENGTH                0x000E
#define WM_PAINT                        0x000F
#define WM_CLOSE                        0x0010
#define WM_QUERYENDSESSION              0x0011
#define WM_QUIT                         0x0012
#define WM_QUERYOPEN                    0x0013
#define WM_ERASEBKGND                   0x0014
#define WM_SYSCOLORCHANGE               0x0015
#define WM_ENDSESSION                   0x0016
#define WM_SHOWWINDOW                   0x0018
#define WM_WININICHANGE                 0x001A
#if(WINVER >= 0x0400)
#define WM_SETTINGCHANGE                WM_WININICHANGE
#endif // WINVER >= 0x0400 


#define WM_DEVMODECHANGE                0x001B
#define WM_ACTIVATEAPP                  0x001C
#define WM_FONTCHANGE                   0x001D
#define WM_TIMECHANGE                   0x001E
#define WM_CANCELMODE                   0x001F
#define WM_SETCURSOR                    0x0020
#define WM_MOUSEACTIVATE                0x0021
#define WM_CHILDACTIVATE                0x0022
#define WM_QUEUESYNC                    0x0023

#define WM_GETMINMAXINFO                0x0024
// end_r_winuser
//
// Struct pointed to by WM_GETMINMAXINFO lParam
 
typedef struct tagMINMAXINFO {
    POINT ptReserved;
    POINT ptMaxSize;
    POINT ptMaxPosition;
    POINT ptMinTrackSize;
    POINT ptMaxTrackSize;
} MINMAXINFO, *PMINMAXINFO, *LPMINMAXINFO;

// begin_r_winuser
#define WM_PAINTICON                    0x0026
#define WM_ICONERASEBKGND               0x0027
#define WM_NEXTDLGCTL                   0x0028
#define WM_SPOOLERSTATUS                0x002A
#define WM_DRAWITEM                     0x002B
#define WM_MEASUREITEM                  0x002C
#define WM_DELETEITEM                   0x002D
#define WM_VKEYTOITEM                   0x002E
#define WM_CHARTOITEM                   0x002F
#define WM_SETFONT                      0x0030
#define WM_GETFONT                      0x0031
#define WM_SETHOTKEY                    0x0032
#define WM_GETHOTKEY                    0x0033
#define WM_QUERYDRAGICON                0x0037
#define WM_COMPAREITEM                  0x0039
#if(WINVER >= 0x0500)
#define WM_GETOBJECT                    0x003D
#endif // WINVER >= 0x0500 
#define WM_COMPACTING                   0x0041
#define WM_COMMNOTIFY                   0x0044  // no longer suported 
#define WM_WINDOWPOSCHANGING            0x0046
#define WM_WINDOWPOSCHANGED             0x0047

#define WM_POWER                        0x0048
//
// wParam for WM_POWER window message and DRV_POWER driver notification
 
#define PWR_OK              1
#define PWR_FAIL            (-1)
#define PWR_SUSPENDREQUEST  1
#define PWR_SUSPENDRESUME   2
#define PWR_CRITICALRESUME  3

#define WM_COPYDATA                     0x004A
#define WM_CANCELJOURNAL                0x004B

// end_r_winuser

//
// lParam of WM_COPYDATA message points to...
 
typedef struct tagCOPYDATASTRUCT {
    DWORD dwData;
    DWORD cbData;
    PVOID lpData;
} COPYDATASTRUCT, *PCOPYDATASTRUCT;

// begin_r_winuser

#if(WINVER >= 0x0400)
#define WM_NOTIFY                       0x004E
#define WM_INPUTLANGCHANGEREQUEST       0x0050
#define WM_INPUTLANGCHANGE              0x0051
#define WM_TCARD                        0x0052
#define WM_HELP                         0x0053
#define WM_USERCHANGED                  0x0054
#define WM_NOTIFYFORMAT                 0x0055

#define NFR_ANSI                             1
#define NFR_UNICODE                          2
#define NF_QUERY                             3
#define NF_REQUERY                           4

#define WM_CONTEXTMENU                  0x007B
#define WM_STYLECHANGING                0x007C
#define WM_STYLECHANGED                 0x007D
#define WM_DISPLAYCHANGE                0x007E
#define WM_GETICON                      0x007F
#define WM_SETICON                      0x0080
#endif // WINVER >= 0x0400 

#define WM_NCCREATE                     0x0081
#define WM_NCDESTROY                    0x0082
#define WM_NCCALCSIZE                   0x0083
#define WM_NCHITTEST                    0x0084
#define WM_NCPAINT                      0x0085
#define WM_NCACTIVATE                   0x0086
#define WM_GETDLGCODE                   0x0087
#define WM_SYNCPAINT                    0x0088
#define WM_NCMOUSEMOVE                  0x00A0
#define WM_NCLBUTTONDOWN                0x00A1
#define WM_NCLBUTTONUP                  0x00A2
#define WM_NCLBUTTONDBLCLK              0x00A3
#define WM_NCRBUTTONDOWN                0x00A4
#define WM_NCRBUTTONUP                  0x00A5
#define WM_NCRBUTTONDBLCLK              0x00A6
#define WM_NCMBUTTONDOWN                0x00A7
#define WM_NCMBUTTONUP                  0x00A8
#define WM_NCMBUTTONDBLCLK              0x00A9

#define WM_KEYFIRST                     0x0100
#define WM_KEYDOWN                      0x0100
#define WM_KEYUP                        0x0101
#define WM_CHAR                         0x0102
#define WM_DEADCHAR                     0x0103
#define WM_SYSKEYDOWN                   0x0104
#define WM_SYSKEYUP                     0x0105
#define WM_SYSCHAR                      0x0106
#define WM_SYSDEADCHAR                  0x0107
#define WM_KEYLAST                      0x0108

#if(WINVER >= 0x0400)
#define WM_IME_STARTCOMPOSITION         0x010D
#define WM_IME_ENDCOMPOSITION           0x010E
#define WM_IME_COMPOSITION              0x010F
#define WM_IME_KEYLAST                  0x010F
#endif // WINVER >= 0x0400 

#define WM_INITDIALOG                   0x0110
#define WM_COMMAND                      0x0111
#define WM_SYSCOMMAND                   0x0112
#define WM_TIMER                        0x0113
#define WM_HSCROLL                      0x0114
#define WM_VSCROLL                      0x0115
#define WM_INITMENU                     0x0116
#define WM_INITMENUPOPUP                0x0117
#define WM_MENUSELECT                   0x011F
#define WM_MENUCHAR                     0x0120
#define WM_ENTERIDLE                    0x0121
#if(WINVER >= 0x0500)
#define WM_MENURBUTTONUP                0x0122
#define WM_MENUDRAG                     0x0123
#define WM_MENUGETOBJECT                0x0124
#define WM_UNINITMENUPOPUP              0x0125
#define WM_MENUCOMMAND                  0x0126
#endif // WINVER >= 0x0500 


#define WM_CTLCOLORMSGBOX               0x0132
#define WM_CTLCOLOREDIT                 0x0133
#define WM_CTLCOLORLISTBOX              0x0134
#define WM_CTLCOLORBTN                  0x0135
#define WM_CTLCOLORDLG                  0x0136
#define WM_CTLCOLORSCROLLBAR            0x0137
#define WM_CTLCOLORSTATIC               0x0138


#define WM_MOUSEFIRST                   0x0200
#define WM_MOUSEMOVE                    0x0200
#define WM_LBUTTONDOWN                  0x0201
#define WM_LBUTTONUP                    0x0202
#define WM_LBUTTONDBLCLK                0x0203
#define WM_RBUTTONDOWN                  0x0204
#define WM_RBUTTONUP                    0x0205
#define WM_RBUTTONDBLCLK                0x0206
#define WM_MBUTTONDOWN                  0x0207
#define WM_MBUTTONUP                    0x0208
#define WM_MBUTTONDBLCLK                0x0209

#if (_WIN32_WINNT >= 0x0400) || (_WIN32_WINDOWS > 0x0400)
#define WM_MOUSEWHEEL                   0x020A
#define WM_MOUSELAST                    0x020A
#else
#define WM_MOUSELAST                    0x0209
#endif // if (_WIN32_WINNT < 0x0400) 

#if(_WIN32_WINNT >= 0x0400)
#define WHEEL_DELTA                     120     // Value for rolling one detent 
#endif // _WIN32_WINNT >= 0x0400 
#if(_WIN32_WINNT >= 0x0400)
#define WHEEL_PAGESCROLL                (UINT_MAX) // Scroll one page 
#endif // _WIN32_WINNT >= 0x0400 

#define WM_PARENTNOTIFY                 0x0210
#define WM_ENTERMENULOOP                0x0211
#define WM_EXITMENULOOP                 0x0212

#if(WINVER >= 0x0400)
#define WM_NEXTMENU                     0x0213
// end_r_winuser

typedef struct tagMDINEXTMENU
{
    HMENU   hmenuIn;
    HMENU   hmenuNext;
    HWND    hwndNext;
} MDINEXTMENU, * PMDINEXTMENU, FAR * LPMDINEXTMENU;

// begin_r_winuser
#define WM_SIZING                       0x0214
#define WM_CAPTURECHANGED               0x0215
#define WM_MOVING                       0x0216
// end_r_winuser
#define WM_POWERBROADCAST               0x0218      // r_winuser pbt
// begin_pbt

#define PBT_APMQUERYSUSPEND             0x0000
#define PBT_APMQUERYSTANDBY             0x0001

#define PBT_APMQUERYSUSPENDFAILED       0x0002
#define PBT_APMQUERYSTANDBYFAILED       0x0003

#define PBT_APMSUSPEND                  0x0004
#define PBT_APMSTANDBY                  0x0005

#define PBT_APMRESUMECRITICAL           0x0006
#define PBT_APMRESUMESUSPEND            0x0007
#define PBT_APMRESUMESTANDBY            0x0008

#define PBTF_APMRESUMEFROMFAILURE       0x00000001

#define PBT_APMBATTERYLOW               0x0009
#define PBT_APMPOWERSTATUSCHANGE        0x000A

#define PBT_APMOEMEVENT                 0x000B
#define PBT_APMRESUMEAUTOMATIC          0x0012
// end_pbt

// begin_r_winuser
#define WM_DEVICECHANGE                 0x0219

#endif // WINVER >= 0x0400 

#define WM_MDICREATE                    0x0220
#define WM_MDIDESTROY                   0x0221
#define WM_MDIACTIVATE                  0x0222
#define WM_MDIRESTORE                   0x0223
#define WM_MDINEXT                      0x0224
#define WM_MDIMAXIMIZE                  0x0225
#define WM_MDITILE                      0x0226
#define WM_MDICASCADE                   0x0227
#define WM_MDIICONARRANGE               0x0228
#define WM_MDIGETACTIVE                 0x0229


#define WM_MDISETMENU                   0x0230
#define WM_ENTERSIZEMOVE                0x0231
#define WM_EXITSIZEMOVE                 0x0232
#define WM_DROPFILES                    0x0233
#define WM_MDIREFRESHMENU               0x0234


#if(WINVER >= 0x0400)
#define WM_IME_SETCONTEXT               0x0281
#define WM_IME_NOTIFY                   0x0282
#define WM_IME_CONTROL                  0x0283
#define WM_IME_COMPOSITIONFULL          0x0284
#define WM_IME_SELECT                   0x0285
#define WM_IME_CHAR                     0x0286
#endif // WINVER >= 0x0400 
#if(WINVER >= 0x0500)
#define WM_IME_REQUEST                  0x0288
#endif // WINVER >= 0x0500 
#if(WINVER >= 0x0400)
#define WM_IME_KEYDOWN                  0x0290
#define WM_IME_KEYUP                    0x0291
#endif // WINVER >= 0x0400 


#if(_WIN32_WINNT >= 0x0400)
#define WM_MOUSEHOVER                   0x02A1
#define WM_MOUSELEAVE                   0x02A3
#endif // _WIN32_WINNT >= 0x0400 

#define WM_CUT                          0x0300
#define WM_COPY                         0x0301
#define WM_PASTE                        0x0302
#define WM_CLEAR                        0x0303
#define WM_UNDO                         0x0304
#define WM_RENDERFORMAT                 0x0305
#define WM_RENDERALLFORMATS             0x0306
#define WM_DESTROYCLIPBOARD             0x0307
#define WM_DRAWCLIPBOARD                0x0308
#define WM_PAINTCLIPBOARD               0x0309
#define WM_VSCROLLCLIPBOARD             0x030A
#define WM_SIZECLIPBOARD                0x030B
#define WM_ASKCBFORMATNAME              0x030C
#define WM_CHANGECBCHAIN                0x030D
#define WM_HSCROLLCLIPBOARD             0x030E
#define WM_QUERYNEWPALETTE              0x030F
#define WM_PALETTEISCHANGING            0x0310
#define WM_PALETTECHANGED               0x0311
#define WM_HOTKEY                       0x0312

#if(WINVER >= 0x0400)
#define WM_PRINT                        0x0317
#define WM_PRINTCLIENT                  0x0318

#define WM_HANDHELDFIRST                0x0358
#define WM_HANDHELDLAST                 0x035F

#define WM_AFXFIRST                     0x0360
#define WM_AFXLAST                      0x037F
#endif // WINVER >= 0x0400 

#define WM_PENWINFIRST                  0x0380
#define WM_PENWINLAST                   0x038F


#if(WINVER >= 0x0400)
#define WM_APP                          0x8000
#endif // WINVER >= 0x0400 
*/

/*

#define VK_LBUTTON        0x01
#define VK_RBUTTON        0x02
#define VK_CANCEL         0x03
#define VK_MBUTTON        0x04    // NOT contiguous with L & RBUTTON

#define VK_BACK           0x08
#define VK_TAB            0x09

#define VK_CLEAR          0x0C
#define VK_RETURN         0x0D

#define VK_SHIFT          0x10
#define VK_CONTROL        0x11
#define VK_MENU           0x12
#define VK_PAUSE          0x13
#define VK_CAPITAL        0x14

#define VK_KANA           0x15
#define VK_HANGEUL        0x15  // old name - should be here for compatibility
#define VK_HANGUL         0x15
#define VK_JUNJA          0x17
#define VK_FINAL          0x18
#define VK_HANJA          0x19
#define VK_KANJI          0x19

#define VK_ESCAPE         0x1B

#define VK_CONVERT        0x1C
#define VK_NONCONVERT     0x1D
#define VK_ACCEPT         0x1E
#define VK_MODECHANGE     0x1F

#define VK_SPACE          0x20
#define VK_PRIOR          0x21
#define VK_NEXT           0x22
#define VK_END            0x23
#define VK_HOME           0x24
#define VK_LEFT           0x25
#define VK_UP             0x26
#define VK_RIGHT          0x27
#define VK_DOWN           0x28
#define VK_SELECT         0x29
#define VK_PRINT          0x2A
#define VK_EXECUTE        0x2B
#define VK_SNAPSHOT       0x2C
#define VK_INSERT         0x2D
#define VK_DELETE         0x2E
#define VK_HELP           0x2F

// VK_0 thru VK_9 are the same as ASCII '0' thru '9' (0x30 - 0x39)
// VK_A thru VK_Z are the same as ASCII 'A' thru 'Z' (0x41 - 0x5A)

#define VK_LWIN           0x5B
#define VK_RWIN           0x5C
#define VK_APPS           0x5D

#define VK_NUMPAD0        0x60
#define VK_NUMPAD1        0x61
#define VK_NUMPAD2        0x62
#define VK_NUMPAD3        0x63
#define VK_NUMPAD4        0x64
#define VK_NUMPAD5        0x65
#define VK_NUMPAD6        0x66
#define VK_NUMPAD7        0x67
#define VK_NUMPAD8        0x68
#define VK_NUMPAD9        0x69
#define VK_MULTIPLY       0x6A
#define VK_ADD            0x6B
#define VK_SEPARATOR      0x6C
#define VK_SUBTRACT       0x6D
#define VK_DECIMAL        0x6E
#define VK_DIVIDE         0x6F
#define VK_F1             0x70
#define VK_F2             0x71
#define VK_F3             0x72
#define VK_F4             0x73
#define VK_F5             0x74
#define VK_F6             0x75
#define VK_F7             0x76
#define VK_F8             0x77
#define VK_F9             0x78
#define VK_F10            0x79
#define VK_F11            0x7A
#define VK_F12            0x7B
#define VK_F13            0x7C
#define VK_F14            0x7D
#define VK_F15            0x7E
#define VK_F16            0x7F
#define VK_F17            0x80
#define VK_F18            0x81
#define VK_F19            0x82
#define VK_F20            0x83
#define VK_F21            0x84
#define VK_F22            0x85
#define VK_F23            0x86
#define VK_F24            0x87

#define VK_NUMLOCK        0x90
#define VK_SCROLL         0x91

//
// VK_L* & VK_R* - left and right Alt, Ctrl and Shift virtual keys.
// Used only as parameters to GetAsyncKeyState() and GetKeyState().
// No other API or message will distinguish left and right keys in this way.
// 
#define VK_LSHIFT         0xA0
#define VK_RSHIFT         0xA1
#define VK_LCONTROL       0xA2
#define VK_RCONTROL       0xA3
#define VK_LMENU          0xA4
#define VK_RMENU          0xA5

#if(WINVER >= 0x0400)
#define VK_PROCESSKEY     0xE5
#endif // WINVER >= 0x0400

#define VK_ATTN           0xF6
#define VK_CRSEL          0xF7
#define VK_EXSEL          0xF8
#define VK_EREOF          0xF9
#define VK_PLAY           0xFA
#define VK_ZOOM           0xFB
#define VK_NONAME         0xFC
#define VK_PA1            0xFD
#define VK_OEM_CLEAR      0xFE

// end_r_winuser

#endif // !NOVIRTUALKEYCODES

*/



/*
TreeView HITTEST デバッグ
	if(ht.flags & TVHT_ABOVE){ debugprintf(L"TVHT_ABOVE"); }
	if(ht.flags & TVHT_BELOW){ debugprintf(L"TVHT_BELOW"); }
	if(ht.flags & TVHT_NOWHERE){ debugprintf(L"TVHT_NOWHERE"); }
	if(ht.flags & TVHT_ONITEM){ debugprintf(L"TVHT_ONITEM"); }
	if(ht.flags & TVHT_ONITEMBUTTON){ debugprintf(L"TVHT_ONITEMBUTTON"); }
	if(ht.flags & TVHT_ONITEMICON){ debugprintf(L"TVHT_ONITEMICON"); }
	if(ht.flags & TVHT_ONITEMINDENT){ debugprintf(L"TVHT_ONITEMINDENT"); }
	if(ht.flags & TVHT_ONITEMLABEL){ debugprintf(L"TVHT_ONITEMLABEL"); }
	if(ht.flags & TVHT_ONITEMRIGHT){ debugprintf(L"TVHT_ONITEMRIGHT"); }
	if(ht.flags & TVHT_ONITEMSTATEICON){ debugprintf(L"TVHT_ONITEMSTATEICON"); }
	if(ht.flags & TVHT_TOLEFT){ debugprintf(L"TVHT_TOLEFT"); }
	if(ht.flags & TVHT_TORIGHT){ debugprintf(L"TVHT_TORIGHT"); }
	debugprintf(L"\n");

*/

#endif
